// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetBikeUserRequest.proto

package com.yzh.rfid.app.request;

public final class GetBikeUserRequest {
  private GetBikeUserRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetBikeUserRequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetBikeUserRequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string session = 1;</code>
     */
    String getSession();
    /**
     * <code>optional string session = 1;</code>
     */
    com.google.protobuf.ByteString
        getSessionBytes();

    /**
     * <code>optional .BikeUserMessage bikeUserMessage = 2;</code>
     */
    boolean hasBikeUserMessage();
    /**
     * <code>optional .BikeUserMessage bikeUserMessage = 2;</code>
     */
    com.yzh.rfid.app.response.BikeUser.BikeUserMessage getBikeUserMessage();
    /**
     * <code>optional .BikeUserMessage bikeUserMessage = 2;</code>
     */
    com.yzh.rfid.app.response.BikeUser.BikeUserMessageOrBuilder getBikeUserMessageOrBuilder();
  }
  /**
   * Protobuf type {@code GetBikeUserRequestMessage}
   */
  public  static final class GetBikeUserRequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetBikeUserRequestMessage)
      GetBikeUserRequestMessageOrBuilder {
    // Use GetBikeUserRequestMessage.newBuilder() to construct.
    private GetBikeUserRequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetBikeUserRequestMessage() {
      session_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetBikeUserRequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              session_ = s;
              break;
            }
            case 18: {
              com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder subBuilder = null;
              if (bikeUserMessage_ != null) {
                subBuilder = bikeUserMessage_.toBuilder();
              }
              bikeUserMessage_ = input.readMessage(com.yzh.rfid.app.response.BikeUser.BikeUserMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bikeUserMessage_);
                bikeUserMessage_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.request.GetBikeUserRequest.internal_static_GetBikeUserRequestMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.request.GetBikeUserRequest.internal_static_GetBikeUserRequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage.class, com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage.Builder.class);
    }

    public static final int SESSION_FIELD_NUMBER = 1;
    private volatile Object session_;
    /**
     * <code>optional string session = 1;</code>
     */
    public String getSession() {
      Object ref = session_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        session_ = s;
        return s;
      }
    }
    /**
     * <code>optional string session = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionBytes() {
      Object ref = session_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        session_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIKEUSERMESSAGE_FIELD_NUMBER = 2;
    private com.yzh.rfid.app.response.BikeUser.BikeUserMessage bikeUserMessage_;
    /**
     * <code>optional .BikeUserMessage bikeUserMessage = 2;</code>
     */
    public boolean hasBikeUserMessage() {
      return bikeUserMessage_ != null;
    }
    /**
     * <code>optional .BikeUserMessage bikeUserMessage = 2;</code>
     */
    public com.yzh.rfid.app.response.BikeUser.BikeUserMessage getBikeUserMessage() {
      return bikeUserMessage_ == null ? com.yzh.rfid.app.response.BikeUser.BikeUserMessage.getDefaultInstance() : bikeUserMessage_;
    }
    /**
     * <code>optional .BikeUserMessage bikeUserMessage = 2;</code>
     */
    public com.yzh.rfid.app.response.BikeUser.BikeUserMessageOrBuilder getBikeUserMessageOrBuilder() {
      return getBikeUserMessage();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSessionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, session_);
      }
      if (bikeUserMessage_ != null) {
        output.writeMessage(2, getBikeUserMessage());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSessionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, session_);
      }
      if (bikeUserMessage_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBikeUserMessage());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage other = (com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage) obj;

      boolean result = true;
      result = result && getSession()
          .equals(other.getSession());
      result = result && (hasBikeUserMessage() == other.hasBikeUserMessage());
      if (hasBikeUserMessage()) {
        result = result && getBikeUserMessage()
            .equals(other.getBikeUserMessage());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSession().hashCode();
      if (hasBikeUserMessage()) {
        hash = (37 * hash) + BIKEUSERMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getBikeUserMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetBikeUserRequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetBikeUserRequestMessage)
        com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.request.GetBikeUserRequest.internal_static_GetBikeUserRequestMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.request.GetBikeUserRequest.internal_static_GetBikeUserRequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage.class, com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        session_ = "";

        if (bikeUserMessageBuilder_ == null) {
          bikeUserMessage_ = null;
        } else {
          bikeUserMessage_ = null;
          bikeUserMessageBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.request.GetBikeUserRequest.internal_static_GetBikeUserRequestMessage_descriptor;
      }

      public com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage build() {
        com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage buildPartial() {
        com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage result = new com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage(this);
        result.session_ = session_;
        if (bikeUserMessageBuilder_ == null) {
          result.bikeUserMessage_ = bikeUserMessage_;
        } else {
          result.bikeUserMessage_ = bikeUserMessageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage) {
          return mergeFrom((com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage other) {
        if (other == com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage.getDefaultInstance()) return this;
        if (!other.getSession().isEmpty()) {
          session_ = other.session_;
          onChanged();
        }
        if (other.hasBikeUserMessage()) {
          mergeBikeUserMessage(other.getBikeUserMessage());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object session_ = "";
      /**
       * <code>optional string session = 1;</code>
       */
      public String getSession() {
        Object ref = session_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          session_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSessionBytes() {
        Object ref = session_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          session_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public Builder setSession(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        session_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public Builder clearSession() {
        
        session_ = getDefaultInstance().getSession();
        onChanged();
        return this;
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public Builder setSessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        session_ = value;
        onChanged();
        return this;
      }

      private com.yzh.rfid.app.response.BikeUser.BikeUserMessage bikeUserMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.BikeUser.BikeUserMessage, com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder, com.yzh.rfid.app.response.BikeUser.BikeUserMessageOrBuilder> bikeUserMessageBuilder_;
      /**
       * <code>optional .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public boolean hasBikeUserMessage() {
        return bikeUserMessageBuilder_ != null || bikeUserMessage_ != null;
      }
      /**
       * <code>optional .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.BikeUser.BikeUserMessage getBikeUserMessage() {
        if (bikeUserMessageBuilder_ == null) {
          return bikeUserMessage_ == null ? com.yzh.rfid.app.response.BikeUser.BikeUserMessage.getDefaultInstance() : bikeUserMessage_;
        } else {
          return bikeUserMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public Builder setBikeUserMessage(com.yzh.rfid.app.response.BikeUser.BikeUserMessage value) {
        if (bikeUserMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bikeUserMessage_ = value;
          onChanged();
        } else {
          bikeUserMessageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public Builder setBikeUserMessage(
          com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder builderForValue) {
        if (bikeUserMessageBuilder_ == null) {
          bikeUserMessage_ = builderForValue.build();
          onChanged();
        } else {
          bikeUserMessageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public Builder mergeBikeUserMessage(com.yzh.rfid.app.response.BikeUser.BikeUserMessage value) {
        if (bikeUserMessageBuilder_ == null) {
          if (bikeUserMessage_ != null) {
            bikeUserMessage_ =
              com.yzh.rfid.app.response.BikeUser.BikeUserMessage.newBuilder(bikeUserMessage_).mergeFrom(value).buildPartial();
          } else {
            bikeUserMessage_ = value;
          }
          onChanged();
        } else {
          bikeUserMessageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public Builder clearBikeUserMessage() {
        if (bikeUserMessageBuilder_ == null) {
          bikeUserMessage_ = null;
          onChanged();
        } else {
          bikeUserMessage_ = null;
          bikeUserMessageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder getBikeUserMessageBuilder() {
        
        onChanged();
        return getBikeUserMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.BikeUser.BikeUserMessageOrBuilder getBikeUserMessageOrBuilder() {
        if (bikeUserMessageBuilder_ != null) {
          return bikeUserMessageBuilder_.getMessageOrBuilder();
        } else {
          return bikeUserMessage_ == null ?
              com.yzh.rfid.app.response.BikeUser.BikeUserMessage.getDefaultInstance() : bikeUserMessage_;
        }
      }
      /**
       * <code>optional .BikeUserMessage bikeUserMessage = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.BikeUser.BikeUserMessage, com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder, com.yzh.rfid.app.response.BikeUser.BikeUserMessageOrBuilder> 
          getBikeUserMessageFieldBuilder() {
        if (bikeUserMessageBuilder_ == null) {
          bikeUserMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yzh.rfid.app.response.BikeUser.BikeUserMessage, com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder, com.yzh.rfid.app.response.BikeUser.BikeUserMessageOrBuilder>(
                  getBikeUserMessage(),
                  getParentForChildren(),
                  isClean());
          bikeUserMessage_ = null;
        }
        return bikeUserMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetBikeUserRequestMessage)
    }

    // @@protoc_insertion_point(class_scope:GetBikeUserRequestMessage)
    private static final com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage();
    }

    public static com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetBikeUserRequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetBikeUserRequestMessage>() {
      public GetBikeUserRequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetBikeUserRequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetBikeUserRequestMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetBikeUserRequestMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.request.GetBikeUserRequest.GetBikeUserRequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetBikeUserRequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetBikeUserRequestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030GetBikeUserRequest.proto\032\016BikeUser.pro" +
      "to\"W\n\031GetBikeUserRequestMessage\022\017\n\007sessi" +
      "on\030\001 \001(\t\022)\n\017bikeUserMessage\030\002 \001(\0132\020.Bike" +
      "UserMessageB2\n\034com.yzh.rfid.app.requ" +
      "estB\022GetBikeUserRequestb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yzh.rfid.app.response.BikeUser.getDescriptor(),
        }, assigner);
    internal_static_GetBikeUserRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetBikeUserRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetBikeUserRequestMessage_descriptor,
        new String[] { "Session", "BikeUserMessage", });
    com.yzh.rfid.app.response.BikeUser.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
