// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetInsuranceRequest.proto

package com.yzh.rfid.app.request;

public final class GetInsuranceRequest {
  private GetInsuranceRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetInsuranceRequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetInsuranceRequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string session = 1;</code>
     */
    String getSession();
    /**
     * <code>optional string session = 1;</code>
     */
    com.google.protobuf.ByteString
        getSessionBytes();

    /**
     * <code>optional .InsuranceMessage insuranceMessage = 2;</code>
     */
    boolean hasInsuranceMessage();
    /**
     * <code>optional .InsuranceMessage insuranceMessage = 2;</code>
     */
    com.yzh.rfid.app.response.Insurance.InsuranceMessage getInsuranceMessage();
    /**
     * <code>optional .InsuranceMessage insuranceMessage = 2;</code>
     */
    com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder getInsuranceMessageOrBuilder();
  }
  /**
   * <pre>
   * [公安app]
   * </pre>
   *
   * Protobuf type {@code GetInsuranceRequestMessage}
   */
  public  static final class GetInsuranceRequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetInsuranceRequestMessage)
      GetInsuranceRequestMessageOrBuilder {
    // Use GetInsuranceRequestMessage.newBuilder() to construct.
    private GetInsuranceRequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetInsuranceRequestMessage() {
      session_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetInsuranceRequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              session_ = s;
              break;
            }
            case 18: {
              com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder subBuilder = null;
              if (insuranceMessage_ != null) {
                subBuilder = insuranceMessage_.toBuilder();
              }
              insuranceMessage_ = input.readMessage(com.yzh.rfid.app.response.Insurance.InsuranceMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(insuranceMessage_);
                insuranceMessage_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.request.GetInsuranceRequest.internal_static_GetInsuranceRequestMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.request.GetInsuranceRequest.internal_static_GetInsuranceRequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage.class, com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage.Builder.class);
    }

    public static final int SESSION_FIELD_NUMBER = 1;
    private volatile Object session_;
    /**
     * <code>optional string session = 1;</code>
     */
    public String getSession() {
      Object ref = session_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        session_ = s;
        return s;
      }
    }
    /**
     * <code>optional string session = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionBytes() {
      Object ref = session_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        session_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INSURANCEMESSAGE_FIELD_NUMBER = 2;
    private com.yzh.rfid.app.response.Insurance.InsuranceMessage insuranceMessage_;
    /**
     * <code>optional .InsuranceMessage insuranceMessage = 2;</code>
     */
    public boolean hasInsuranceMessage() {
      return insuranceMessage_ != null;
    }
    /**
     * <code>optional .InsuranceMessage insuranceMessage = 2;</code>
     */
    public com.yzh.rfid.app.response.Insurance.InsuranceMessage getInsuranceMessage() {
      return insuranceMessage_ == null ? com.yzh.rfid.app.response.Insurance.InsuranceMessage.getDefaultInstance() : insuranceMessage_;
    }
    /**
     * <code>optional .InsuranceMessage insuranceMessage = 2;</code>
     */
    public com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder getInsuranceMessageOrBuilder() {
      return getInsuranceMessage();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSessionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, session_);
      }
      if (insuranceMessage_ != null) {
        output.writeMessage(2, getInsuranceMessage());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSessionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, session_);
      }
      if (insuranceMessage_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getInsuranceMessage());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage other = (com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage) obj;

      boolean result = true;
      result = result && getSession()
          .equals(other.getSession());
      result = result && (hasInsuranceMessage() == other.hasInsuranceMessage());
      if (hasInsuranceMessage()) {
        result = result && getInsuranceMessage()
            .equals(other.getInsuranceMessage());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSession().hashCode();
      if (hasInsuranceMessage()) {
        hash = (37 * hash) + INSURANCEMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getInsuranceMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [公安app]
     * </pre>
     *
     * Protobuf type {@code GetInsuranceRequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetInsuranceRequestMessage)
        com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.request.GetInsuranceRequest.internal_static_GetInsuranceRequestMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.request.GetInsuranceRequest.internal_static_GetInsuranceRequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage.class, com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        session_ = "";

        if (insuranceMessageBuilder_ == null) {
          insuranceMessage_ = null;
        } else {
          insuranceMessage_ = null;
          insuranceMessageBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.request.GetInsuranceRequest.internal_static_GetInsuranceRequestMessage_descriptor;
      }

      public com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage build() {
        com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage buildPartial() {
        com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage result = new com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage(this);
        result.session_ = session_;
        if (insuranceMessageBuilder_ == null) {
          result.insuranceMessage_ = insuranceMessage_;
        } else {
          result.insuranceMessage_ = insuranceMessageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage) {
          return mergeFrom((com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage other) {
        if (other == com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage.getDefaultInstance()) return this;
        if (!other.getSession().isEmpty()) {
          session_ = other.session_;
          onChanged();
        }
        if (other.hasInsuranceMessage()) {
          mergeInsuranceMessage(other.getInsuranceMessage());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object session_ = "";
      /**
       * <code>optional string session = 1;</code>
       */
      public String getSession() {
        Object ref = session_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          session_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSessionBytes() {
        Object ref = session_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          session_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public Builder setSession(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        session_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public Builder clearSession() {
        
        session_ = getDefaultInstance().getSession();
        onChanged();
        return this;
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public Builder setSessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        session_ = value;
        onChanged();
        return this;
      }

      private com.yzh.rfid.app.response.Insurance.InsuranceMessage insuranceMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.Insurance.InsuranceMessage, com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder, com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder> insuranceMessageBuilder_;
      /**
       * <code>optional .InsuranceMessage insuranceMessage = 2;</code>
       */
      public boolean hasInsuranceMessage() {
        return insuranceMessageBuilder_ != null || insuranceMessage_ != null;
      }
      /**
       * <code>optional .InsuranceMessage insuranceMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.Insurance.InsuranceMessage getInsuranceMessage() {
        if (insuranceMessageBuilder_ == null) {
          return insuranceMessage_ == null ? com.yzh.rfid.app.response.Insurance.InsuranceMessage.getDefaultInstance() : insuranceMessage_;
        } else {
          return insuranceMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .InsuranceMessage insuranceMessage = 2;</code>
       */
      public Builder setInsuranceMessage(com.yzh.rfid.app.response.Insurance.InsuranceMessage value) {
        if (insuranceMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          insuranceMessage_ = value;
          onChanged();
        } else {
          insuranceMessageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .InsuranceMessage insuranceMessage = 2;</code>
       */
      public Builder setInsuranceMessage(
          com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder builderForValue) {
        if (insuranceMessageBuilder_ == null) {
          insuranceMessage_ = builderForValue.build();
          onChanged();
        } else {
          insuranceMessageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .InsuranceMessage insuranceMessage = 2;</code>
       */
      public Builder mergeInsuranceMessage(com.yzh.rfid.app.response.Insurance.InsuranceMessage value) {
        if (insuranceMessageBuilder_ == null) {
          if (insuranceMessage_ != null) {
            insuranceMessage_ =
              com.yzh.rfid.app.response.Insurance.InsuranceMessage.newBuilder(insuranceMessage_).mergeFrom(value).buildPartial();
          } else {
            insuranceMessage_ = value;
          }
          onChanged();
        } else {
          insuranceMessageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .InsuranceMessage insuranceMessage = 2;</code>
       */
      public Builder clearInsuranceMessage() {
        if (insuranceMessageBuilder_ == null) {
          insuranceMessage_ = null;
          onChanged();
        } else {
          insuranceMessage_ = null;
          insuranceMessageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .InsuranceMessage insuranceMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder getInsuranceMessageBuilder() {
        
        onChanged();
        return getInsuranceMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .InsuranceMessage insuranceMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder getInsuranceMessageOrBuilder() {
        if (insuranceMessageBuilder_ != null) {
          return insuranceMessageBuilder_.getMessageOrBuilder();
        } else {
          return insuranceMessage_ == null ?
              com.yzh.rfid.app.response.Insurance.InsuranceMessage.getDefaultInstance() : insuranceMessage_;
        }
      }
      /**
       * <code>optional .InsuranceMessage insuranceMessage = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.Insurance.InsuranceMessage, com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder, com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder> 
          getInsuranceMessageFieldBuilder() {
        if (insuranceMessageBuilder_ == null) {
          insuranceMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yzh.rfid.app.response.Insurance.InsuranceMessage, com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder, com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder>(
                  getInsuranceMessage(),
                  getParentForChildren(),
                  isClean());
          insuranceMessage_ = null;
        }
        return insuranceMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetInsuranceRequestMessage)
    }

    // @@protoc_insertion_point(class_scope:GetInsuranceRequestMessage)
    private static final com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage();
    }

    public static com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetInsuranceRequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetInsuranceRequestMessage>() {
      public GetInsuranceRequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetInsuranceRequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetInsuranceRequestMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetInsuranceRequestMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.request.GetInsuranceRequest.GetInsuranceRequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetInsuranceRequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetInsuranceRequestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031GetInsuranceRequest.proto\032\017Insurance.p" +
      "roto\"Z\n\032GetInsuranceRequestMessage\022\017\n\007se" +
      "ssion\030\001 \001(\t\022+\n\020insuranceMessage\030\002 \001(\0132\021." +
      "InsuranceMessageB3\n\034com.yzh.rfid.app" +
      ".requestB\023GetInsuranceRequestb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yzh.rfid.app.response.Insurance.getDescriptor(),
        }, assigner);
    internal_static_GetInsuranceRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetInsuranceRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetInsuranceRequestMessage_descriptor,
        new String[] { "Session", "InsuranceMessage", });
    com.yzh.rfid.app.response.Insurance.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
