// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BikeLost.proto

package com.yzh.rfid.app.response;

public final class BikeLost {
  private BikeLost() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BikeLostMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BikeLostMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     * 车主id
     * </pre>
     *
     * <code>optional int64 userId = 2;</code>
     */
    long getUserId();

    /**
     * <pre>
     * 车主姓名
     * </pre>
     *
     * <code>optional string userName = 3;</code>
     */
    String getUserName();
    /**
     * <pre>
     * 车主姓名
     * </pre>
     *
     * <code>optional string userName = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <pre>
     * 车主身份证号
     * </pre>
     *
     * <code>optional string userIdCard = 4;</code>
     */
    String getUserIdCard();
    /**
     * <pre>
     * 车主身份证号
     * </pre>
     *
     * <code>optional string userIdCard = 4;</code>
     */
    com.google.protobuf.ByteString
        getUserIdCardBytes();

    /**
     * <pre>
     * 车辆id
     * </pre>
     *
     * <code>optional int64 bikeId = 5;</code>
     */
    long getBikeId();

    /**
     * <pre>
     *  车牌号
     * </pre>
     *
     * <code>optional string plateNumber = 6;</code>
     */
    String getPlateNumber();
    /**
     * <pre>
     *  车牌号
     * </pre>
     *
     * <code>optional string plateNumber = 6;</code>
     */
    com.google.protobuf.ByteString
        getPlateNumberBytes();

    /**
     * <pre>
     *  报案日期
     * </pre>
     *
     * <code>optional int64 reportDate = 7;</code>
     */
    long getReportDate();

    /**
     * <pre>
     *   区域id
     * </pre>
     *
     * <code>optional int64 areaId = 8;</code>
     */
    long getAreaId();

    /**
     * <pre>
     *  车辆丢失地址
     * </pre>
     *
     * <code>optional string lostAddress = 9;</code>
     */
    String getLostAddress();
    /**
     * <pre>
     *  车辆丢失地址
     * </pre>
     *
     * <code>optional string lostAddress = 9;</code>
     */
    com.google.protobuf.ByteString
        getLostAddressBytes();

    /**
     * <pre>
     *   车辆丢失时间
     * </pre>
     *
     * <code>optional int64 lostTime = 10;</code>
     */
    long getLostTime();

    /**
     * <pre>
     *   丢失描述
     * </pre>
     *
     * <code>optional string lostDescription = 11;</code>
     */
    String getLostDescription();
    /**
     * <pre>
     *   丢失描述
     * </pre>
     *
     * <code>optional string lostDescription = 11;</code>
     */
    com.google.protobuf.ByteString
        getLostDescriptionBytes();

    /**
     * <pre>
     *   拒绝原因
     * </pre>
     *
     * <code>optional string rejectReason = 12;</code>
     */
    String getRejectReason();
    /**
     * <pre>
     *   拒绝原因
     * </pre>
     *
     * <code>optional string rejectReason = 12;</code>
     */
    com.google.protobuf.ByteString
        getRejectReasonBytes();

    /**
     * <pre>
     * 状态：0.申请丢失1.审核通过 ，2. 申请丢失驳回，3.已找回 4.已丢失，启动索赔（申请丢失后10天，天数待定）
     * </pre>
     *
     * <code>optional string status = 13;</code>
     */
    String getStatus();
    /**
     * <pre>
     * 状态：0.申请丢失1.审核通过 ，2. 申请丢失驳回，3.已找回 4.已丢失，启动索赔（申请丢失后10天，天数待定）
     * </pre>
     *
     * <code>optional string status = 13;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <pre>
     *  创建者
     * </pre>
     *
     * <code>optional string createBy = 14;</code>
     */
    String getCreateBy();
    /**
     * <pre>
     *  创建者
     * </pre>
     *
     * <code>optional string createBy = 14;</code>
     */
    com.google.protobuf.ByteString
        getCreateByBytes();

    /**
     * <pre>
     *  创建时间
     * </pre>
     *
     * <code>optional int64 createDate = 15;</code>
     */
    long getCreateDate();

    /**
     * <pre>
     *  更新者
     * </pre>
     *
     * <code>optional string updateBy = 16;</code>
     */
    String getUpdateBy();
    /**
     * <pre>
     *  更新者
     * </pre>
     *
     * <code>optional string updateBy = 16;</code>
     */
    com.google.protobuf.ByteString
        getUpdateByBytes();

    /**
     * <pre>
     *  更新时间
     * </pre>
     *
     * <code>optional int64 updateDate = 17;</code>
     */
    long getUpdateDate();

    /**
     * <pre>
     * 公司id
     * </pre>
     *
     * <code>optional int64 companyId = 18;</code>
     */
    long getCompanyId();

    /**
     * <pre>
     *删除标志
     * </pre>
     *
     * <code>optional string delFlag = 19;</code>
     */
    String getDelFlag();
    /**
     * <pre>
     *删除标志
     * </pre>
     *
     * <code>optional string delFlag = 19;</code>
     */
    com.google.protobuf.ByteString
        getDelFlagBytes();

    /**
     * <pre>
     * 卡号
     * </pre>
     *
     * <code>optional string cardNo = 20;</code>
     */
    String getCardNo();
    /**
     * <pre>
     * 卡号
     * </pre>
     *
     * <code>optional string cardNo = 20;</code>
     */
    com.google.protobuf.ByteString
        getCardNoBytes();
  }
  /**
   * Protobuf type {@code BikeLostMessage}
   */
  public  static final class BikeLostMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BikeLostMessage)
      BikeLostMessageOrBuilder {
    // Use BikeLostMessage.newBuilder() to construct.
    private BikeLostMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BikeLostMessage() {
      id_ = 0L;
      userId_ = 0L;
      userName_ = "";
      userIdCard_ = "";
      bikeId_ = 0L;
      plateNumber_ = "";
      reportDate_ = 0L;
      areaId_ = 0L;
      lostAddress_ = "";
      lostTime_ = 0L;
      lostDescription_ = "";
      rejectReason_ = "";
      status_ = "";
      createBy_ = "";
      createDate_ = 0L;
      updateBy_ = "";
      updateDate_ = 0L;
      companyId_ = 0L;
      delFlag_ = "";
      cardNo_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BikeLostMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              userId_ = input.readInt64();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              userIdCard_ = s;
              break;
            }
            case 40: {

              bikeId_ = input.readInt64();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              plateNumber_ = s;
              break;
            }
            case 56: {

              reportDate_ = input.readInt64();
              break;
            }
            case 64: {

              areaId_ = input.readInt64();
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              lostAddress_ = s;
              break;
            }
            case 80: {

              lostTime_ = input.readInt64();
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              lostDescription_ = s;
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              rejectReason_ = s;
              break;
            }
            case 106: {
              String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            case 114: {
              String s = input.readStringRequireUtf8();

              createBy_ = s;
              break;
            }
            case 120: {

              createDate_ = input.readInt64();
              break;
            }
            case 130: {
              String s = input.readStringRequireUtf8();

              updateBy_ = s;
              break;
            }
            case 136: {

              updateDate_ = input.readInt64();
              break;
            }
            case 144: {

              companyId_ = input.readInt64();
              break;
            }
            case 154: {
              String s = input.readStringRequireUtf8();

              delFlag_ = s;
              break;
            }
            case 162: {
              String s = input.readStringRequireUtf8();

              cardNo_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.response.BikeLost.internal_static_BikeLostMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.response.BikeLost.internal_static_BikeLostMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.response.BikeLost.BikeLostMessage.class, com.yzh.rfid.app.response.BikeLost.BikeLostMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private long userId_;
    /**
     * <pre>
     * 车主id
     * </pre>
     *
     * <code>optional int64 userId = 2;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int USERNAME_FIELD_NUMBER = 3;
    private volatile Object userName_;
    /**
     * <pre>
     * 车主姓名
     * </pre>
     *
     * <code>optional string userName = 3;</code>
     */
    public String getUserName() {
      Object ref = userName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 车主姓名
     * </pre>
     *
     * <code>optional string userName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERIDCARD_FIELD_NUMBER = 4;
    private volatile Object userIdCard_;
    /**
     * <pre>
     * 车主身份证号
     * </pre>
     *
     * <code>optional string userIdCard = 4;</code>
     */
    public String getUserIdCard() {
      Object ref = userIdCard_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userIdCard_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 车主身份证号
     * </pre>
     *
     * <code>optional string userIdCard = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdCardBytes() {
      Object ref = userIdCard_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userIdCard_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIKEID_FIELD_NUMBER = 5;
    private long bikeId_;
    /**
     * <pre>
     * 车辆id
     * </pre>
     *
     * <code>optional int64 bikeId = 5;</code>
     */
    public long getBikeId() {
      return bikeId_;
    }

    public static final int PLATENUMBER_FIELD_NUMBER = 6;
    private volatile Object plateNumber_;
    /**
     * <pre>
     *  车牌号
     * </pre>
     *
     * <code>optional string plateNumber = 6;</code>
     */
    public String getPlateNumber() {
      Object ref = plateNumber_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        plateNumber_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  车牌号
     * </pre>
     *
     * <code>optional string plateNumber = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPlateNumberBytes() {
      Object ref = plateNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        plateNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REPORTDATE_FIELD_NUMBER = 7;
    private long reportDate_;
    /**
     * <pre>
     *  报案日期
     * </pre>
     *
     * <code>optional int64 reportDate = 7;</code>
     */
    public long getReportDate() {
      return reportDate_;
    }

    public static final int AREAID_FIELD_NUMBER = 8;
    private long areaId_;
    /**
     * <pre>
     *   区域id
     * </pre>
     *
     * <code>optional int64 areaId = 8;</code>
     */
    public long getAreaId() {
      return areaId_;
    }

    public static final int LOSTADDRESS_FIELD_NUMBER = 9;
    private volatile Object lostAddress_;
    /**
     * <pre>
     *  车辆丢失地址
     * </pre>
     *
     * <code>optional string lostAddress = 9;</code>
     */
    public String getLostAddress() {
      Object ref = lostAddress_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        lostAddress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  车辆丢失地址
     * </pre>
     *
     * <code>optional string lostAddress = 9;</code>
     */
    public com.google.protobuf.ByteString
        getLostAddressBytes() {
      Object ref = lostAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        lostAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOSTTIME_FIELD_NUMBER = 10;
    private long lostTime_;
    /**
     * <pre>
     *   车辆丢失时间
     * </pre>
     *
     * <code>optional int64 lostTime = 10;</code>
     */
    public long getLostTime() {
      return lostTime_;
    }

    public static final int LOSTDESCRIPTION_FIELD_NUMBER = 11;
    private volatile Object lostDescription_;
    /**
     * <pre>
     *   丢失描述
     * </pre>
     *
     * <code>optional string lostDescription = 11;</code>
     */
    public String getLostDescription() {
      Object ref = lostDescription_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        lostDescription_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *   丢失描述
     * </pre>
     *
     * <code>optional string lostDescription = 11;</code>
     */
    public com.google.protobuf.ByteString
        getLostDescriptionBytes() {
      Object ref = lostDescription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        lostDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REJECTREASON_FIELD_NUMBER = 12;
    private volatile Object rejectReason_;
    /**
     * <pre>
     *   拒绝原因
     * </pre>
     *
     * <code>optional string rejectReason = 12;</code>
     */
    public String getRejectReason() {
      Object ref = rejectReason_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        rejectReason_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *   拒绝原因
     * </pre>
     *
     * <code>optional string rejectReason = 12;</code>
     */
    public com.google.protobuf.ByteString
        getRejectReasonBytes() {
      Object ref = rejectReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        rejectReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 13;
    private volatile Object status_;
    /**
     * <pre>
     * 状态：0.申请丢失1.审核通过 ，2. 申请丢失驳回，3.已找回 4.已丢失，启动索赔（申请丢失后10天，天数待定）
     * </pre>
     *
     * <code>optional string status = 13;</code>
     */
    public String getStatus() {
      Object ref = status_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 状态：0.申请丢失1.审核通过 ，2. 申请丢失驳回，3.已找回 4.已丢失，启动索赔（申请丢失后10天，天数待定）
     * </pre>
     *
     * <code>optional string status = 13;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEBY_FIELD_NUMBER = 14;
    private volatile Object createBy_;
    /**
     * <pre>
     *  创建者
     * </pre>
     *
     * <code>optional string createBy = 14;</code>
     */
    public String getCreateBy() {
      Object ref = createBy_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        createBy_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  创建者
     * </pre>
     *
     * <code>optional string createBy = 14;</code>
     */
    public com.google.protobuf.ByteString
        getCreateByBytes() {
      Object ref = createBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        createBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEDATE_FIELD_NUMBER = 15;
    private long createDate_;
    /**
     * <pre>
     *  创建时间
     * </pre>
     *
     * <code>optional int64 createDate = 15;</code>
     */
    public long getCreateDate() {
      return createDate_;
    }

    public static final int UPDATEBY_FIELD_NUMBER = 16;
    private volatile Object updateBy_;
    /**
     * <pre>
     *  更新者
     * </pre>
     *
     * <code>optional string updateBy = 16;</code>
     */
    public String getUpdateBy() {
      Object ref = updateBy_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        updateBy_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  更新者
     * </pre>
     *
     * <code>optional string updateBy = 16;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateByBytes() {
      Object ref = updateBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        updateBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATEDATE_FIELD_NUMBER = 17;
    private long updateDate_;
    /**
     * <pre>
     *  更新时间
     * </pre>
     *
     * <code>optional int64 updateDate = 17;</code>
     */
    public long getUpdateDate() {
      return updateDate_;
    }

    public static final int COMPANYID_FIELD_NUMBER = 18;
    private long companyId_;
    /**
     * <pre>
     * 公司id
     * </pre>
     *
     * <code>optional int64 companyId = 18;</code>
     */
    public long getCompanyId() {
      return companyId_;
    }

    public static final int DELFLAG_FIELD_NUMBER = 19;
    private volatile Object delFlag_;
    /**
     * <pre>
     *删除标志
     * </pre>
     *
     * <code>optional string delFlag = 19;</code>
     */
    public String getDelFlag() {
      Object ref = delFlag_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        delFlag_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *删除标志
     * </pre>
     *
     * <code>optional string delFlag = 19;</code>
     */
    public com.google.protobuf.ByteString
        getDelFlagBytes() {
      Object ref = delFlag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        delFlag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARDNO_FIELD_NUMBER = 20;
    private volatile Object cardNo_;
    /**
     * <pre>
     * 卡号
     * </pre>
     *
     * <code>optional string cardNo = 20;</code>
     */
    public String getCardNo() {
      Object ref = cardNo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cardNo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 卡号
     * </pre>
     *
     * <code>optional string cardNo = 20;</code>
     */
    public com.google.protobuf.ByteString
        getCardNoBytes() {
      Object ref = cardNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cardNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (userId_ != 0L) {
        output.writeInt64(2, userId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userName_);
      }
      if (!getUserIdCardBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userIdCard_);
      }
      if (bikeId_ != 0L) {
        output.writeInt64(5, bikeId_);
      }
      if (!getPlateNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, plateNumber_);
      }
      if (reportDate_ != 0L) {
        output.writeInt64(7, reportDate_);
      }
      if (areaId_ != 0L) {
        output.writeInt64(8, areaId_);
      }
      if (!getLostAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, lostAddress_);
      }
      if (lostTime_ != 0L) {
        output.writeInt64(10, lostTime_);
      }
      if (!getLostDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, lostDescription_);
      }
      if (!getRejectReasonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, rejectReason_);
      }
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, status_);
      }
      if (!getCreateByBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, createBy_);
      }
      if (createDate_ != 0L) {
        output.writeInt64(15, createDate_);
      }
      if (!getUpdateByBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, updateBy_);
      }
      if (updateDate_ != 0L) {
        output.writeInt64(17, updateDate_);
      }
      if (companyId_ != 0L) {
        output.writeInt64(18, companyId_);
      }
      if (!getDelFlagBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 19, delFlag_);
      }
      if (!getCardNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 20, cardNo_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userName_);
      }
      if (!getUserIdCardBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userIdCard_);
      }
      if (bikeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, bikeId_);
      }
      if (!getPlateNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, plateNumber_);
      }
      if (reportDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, reportDate_);
      }
      if (areaId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, areaId_);
      }
      if (!getLostAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, lostAddress_);
      }
      if (lostTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, lostTime_);
      }
      if (!getLostDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, lostDescription_);
      }
      if (!getRejectReasonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, rejectReason_);
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, status_);
      }
      if (!getCreateByBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, createBy_);
      }
      if (createDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(15, createDate_);
      }
      if (!getUpdateByBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, updateBy_);
      }
      if (updateDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(17, updateDate_);
      }
      if (companyId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(18, companyId_);
      }
      if (!getDelFlagBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, delFlag_);
      }
      if (!getCardNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, cardNo_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.response.BikeLost.BikeLostMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.response.BikeLost.BikeLostMessage other = (com.yzh.rfid.app.response.BikeLost.BikeLostMessage) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getUserId()
          == other.getUserId());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && getUserIdCard()
          .equals(other.getUserIdCard());
      result = result && (getBikeId()
          == other.getBikeId());
      result = result && getPlateNumber()
          .equals(other.getPlateNumber());
      result = result && (getReportDate()
          == other.getReportDate());
      result = result && (getAreaId()
          == other.getAreaId());
      result = result && getLostAddress()
          .equals(other.getLostAddress());
      result = result && (getLostTime()
          == other.getLostTime());
      result = result && getLostDescription()
          .equals(other.getLostDescription());
      result = result && getRejectReason()
          .equals(other.getRejectReason());
      result = result && getStatus()
          .equals(other.getStatus());
      result = result && getCreateBy()
          .equals(other.getCreateBy());
      result = result && (getCreateDate()
          == other.getCreateDate());
      result = result && getUpdateBy()
          .equals(other.getUpdateBy());
      result = result && (getUpdateDate()
          == other.getUpdateDate());
      result = result && (getCompanyId()
          == other.getCompanyId());
      result = result && getDelFlag()
          .equals(other.getDelFlag());
      result = result && getCardNo()
          .equals(other.getCardNo());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + USERIDCARD_FIELD_NUMBER;
      hash = (53 * hash) + getUserIdCard().hashCode();
      hash = (37 * hash) + BIKEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBikeId());
      hash = (37 * hash) + PLATENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPlateNumber().hashCode();
      hash = (37 * hash) + REPORTDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReportDate());
      hash = (37 * hash) + AREAID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAreaId());
      hash = (37 * hash) + LOSTADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getLostAddress().hashCode();
      hash = (37 * hash) + LOSTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLostTime());
      hash = (37 * hash) + LOSTDESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getLostDescription().hashCode();
      hash = (37 * hash) + REJECTREASON_FIELD_NUMBER;
      hash = (53 * hash) + getRejectReason().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + CREATEBY_FIELD_NUMBER;
      hash = (53 * hash) + getCreateBy().hashCode();
      hash = (37 * hash) + CREATEDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateDate());
      hash = (37 * hash) + UPDATEBY_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateBy().hashCode();
      hash = (37 * hash) + UPDATEDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdateDate());
      hash = (37 * hash) + COMPANYID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCompanyId());
      hash = (37 * hash) + DELFLAG_FIELD_NUMBER;
      hash = (53 * hash) + getDelFlag().hashCode();
      hash = (37 * hash) + CARDNO_FIELD_NUMBER;
      hash = (53 * hash) + getCardNo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.response.BikeLost.BikeLostMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.BikeLost.BikeLostMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.BikeLost.BikeLostMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.BikeLost.BikeLostMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.BikeLost.BikeLostMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.BikeLost.BikeLostMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.BikeLost.BikeLostMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.BikeLost.BikeLostMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.BikeLost.BikeLostMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.BikeLost.BikeLostMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.response.BikeLost.BikeLostMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BikeLostMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BikeLostMessage)
        com.yzh.rfid.app.response.BikeLost.BikeLostMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.response.BikeLost.internal_static_BikeLostMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.response.BikeLost.internal_static_BikeLostMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.response.BikeLost.BikeLostMessage.class, com.yzh.rfid.app.response.BikeLost.BikeLostMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.response.BikeLost.BikeLostMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        userId_ = 0L;

        userName_ = "";

        userIdCard_ = "";

        bikeId_ = 0L;

        plateNumber_ = "";

        reportDate_ = 0L;

        areaId_ = 0L;

        lostAddress_ = "";

        lostTime_ = 0L;

        lostDescription_ = "";

        rejectReason_ = "";

        status_ = "";

        createBy_ = "";

        createDate_ = 0L;

        updateBy_ = "";

        updateDate_ = 0L;

        companyId_ = 0L;

        delFlag_ = "";

        cardNo_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.response.BikeLost.internal_static_BikeLostMessage_descriptor;
      }

      public com.yzh.rfid.app.response.BikeLost.BikeLostMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.response.BikeLost.BikeLostMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.response.BikeLost.BikeLostMessage build() {
        com.yzh.rfid.app.response.BikeLost.BikeLostMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.response.BikeLost.BikeLostMessage buildPartial() {
        com.yzh.rfid.app.response.BikeLost.BikeLostMessage result = new com.yzh.rfid.app.response.BikeLost.BikeLostMessage(this);
        result.id_ = id_;
        result.userId_ = userId_;
        result.userName_ = userName_;
        result.userIdCard_ = userIdCard_;
        result.bikeId_ = bikeId_;
        result.plateNumber_ = plateNumber_;
        result.reportDate_ = reportDate_;
        result.areaId_ = areaId_;
        result.lostAddress_ = lostAddress_;
        result.lostTime_ = lostTime_;
        result.lostDescription_ = lostDescription_;
        result.rejectReason_ = rejectReason_;
        result.status_ = status_;
        result.createBy_ = createBy_;
        result.createDate_ = createDate_;
        result.updateBy_ = updateBy_;
        result.updateDate_ = updateDate_;
        result.companyId_ = companyId_;
        result.delFlag_ = delFlag_;
        result.cardNo_ = cardNo_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.response.BikeLost.BikeLostMessage) {
          return mergeFrom((com.yzh.rfid.app.response.BikeLost.BikeLostMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.response.BikeLost.BikeLostMessage other) {
        if (other == com.yzh.rfid.app.response.BikeLost.BikeLostMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getUserIdCard().isEmpty()) {
          userIdCard_ = other.userIdCard_;
          onChanged();
        }
        if (other.getBikeId() != 0L) {
          setBikeId(other.getBikeId());
        }
        if (!other.getPlateNumber().isEmpty()) {
          plateNumber_ = other.plateNumber_;
          onChanged();
        }
        if (other.getReportDate() != 0L) {
          setReportDate(other.getReportDate());
        }
        if (other.getAreaId() != 0L) {
          setAreaId(other.getAreaId());
        }
        if (!other.getLostAddress().isEmpty()) {
          lostAddress_ = other.lostAddress_;
          onChanged();
        }
        if (other.getLostTime() != 0L) {
          setLostTime(other.getLostTime());
        }
        if (!other.getLostDescription().isEmpty()) {
          lostDescription_ = other.lostDescription_;
          onChanged();
        }
        if (!other.getRejectReason().isEmpty()) {
          rejectReason_ = other.rejectReason_;
          onChanged();
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        if (!other.getCreateBy().isEmpty()) {
          createBy_ = other.createBy_;
          onChanged();
        }
        if (other.getCreateDate() != 0L) {
          setCreateDate(other.getCreateDate());
        }
        if (!other.getUpdateBy().isEmpty()) {
          updateBy_ = other.updateBy_;
          onChanged();
        }
        if (other.getUpdateDate() != 0L) {
          setUpdateDate(other.getUpdateDate());
        }
        if (other.getCompanyId() != 0L) {
          setCompanyId(other.getCompanyId());
        }
        if (!other.getDelFlag().isEmpty()) {
          delFlag_ = other.delFlag_;
          onChanged();
        }
        if (!other.getCardNo().isEmpty()) {
          cardNo_ = other.cardNo_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.response.BikeLost.BikeLostMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.response.BikeLost.BikeLostMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <pre>
       * 车主id
       * </pre>
       *
       * <code>optional int64 userId = 2;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <pre>
       * 车主id
       * </pre>
       *
       * <code>optional int64 userId = 2;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 车主id
       * </pre>
       *
       * <code>optional int64 userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private Object userName_ = "";
      /**
       * <pre>
       * 车主姓名
       * </pre>
       *
       * <code>optional string userName = 3;</code>
       */
      public String getUserName() {
        Object ref = userName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 车主姓名
       * </pre>
       *
       * <code>optional string userName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 车主姓名
       * </pre>
       *
       * <code>optional string userName = 3;</code>
       */
      public Builder setUserName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 车主姓名
       * </pre>
       *
       * <code>optional string userName = 3;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 车主姓名
       * </pre>
       *
       * <code>optional string userName = 3;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private Object userIdCard_ = "";
      /**
       * <pre>
       * 车主身份证号
       * </pre>
       *
       * <code>optional string userIdCard = 4;</code>
       */
      public String getUserIdCard() {
        Object ref = userIdCard_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userIdCard_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 车主身份证号
       * </pre>
       *
       * <code>optional string userIdCard = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdCardBytes() {
        Object ref = userIdCard_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userIdCard_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 车主身份证号
       * </pre>
       *
       * <code>optional string userIdCard = 4;</code>
       */
      public Builder setUserIdCard(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userIdCard_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 车主身份证号
       * </pre>
       *
       * <code>optional string userIdCard = 4;</code>
       */
      public Builder clearUserIdCard() {
        
        userIdCard_ = getDefaultInstance().getUserIdCard();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 车主身份证号
       * </pre>
       *
       * <code>optional string userIdCard = 4;</code>
       */
      public Builder setUserIdCardBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userIdCard_ = value;
        onChanged();
        return this;
      }

      private long bikeId_ ;
      /**
       * <pre>
       * 车辆id
       * </pre>
       *
       * <code>optional int64 bikeId = 5;</code>
       */
      public long getBikeId() {
        return bikeId_;
      }
      /**
       * <pre>
       * 车辆id
       * </pre>
       *
       * <code>optional int64 bikeId = 5;</code>
       */
      public Builder setBikeId(long value) {
        
        bikeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 车辆id
       * </pre>
       *
       * <code>optional int64 bikeId = 5;</code>
       */
      public Builder clearBikeId() {
        
        bikeId_ = 0L;
        onChanged();
        return this;
      }

      private Object plateNumber_ = "";
      /**
       * <pre>
       *  车牌号
       * </pre>
       *
       * <code>optional string plateNumber = 6;</code>
       */
      public String getPlateNumber() {
        Object ref = plateNumber_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          plateNumber_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *  车牌号
       * </pre>
       *
       * <code>optional string plateNumber = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPlateNumberBytes() {
        Object ref = plateNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          plateNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  车牌号
       * </pre>
       *
       * <code>optional string plateNumber = 6;</code>
       */
      public Builder setPlateNumber(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        plateNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  车牌号
       * </pre>
       *
       * <code>optional string plateNumber = 6;</code>
       */
      public Builder clearPlateNumber() {
        
        plateNumber_ = getDefaultInstance().getPlateNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  车牌号
       * </pre>
       *
       * <code>optional string plateNumber = 6;</code>
       */
      public Builder setPlateNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        plateNumber_ = value;
        onChanged();
        return this;
      }

      private long reportDate_ ;
      /**
       * <pre>
       *  报案日期
       * </pre>
       *
       * <code>optional int64 reportDate = 7;</code>
       */
      public long getReportDate() {
        return reportDate_;
      }
      /**
       * <pre>
       *  报案日期
       * </pre>
       *
       * <code>optional int64 reportDate = 7;</code>
       */
      public Builder setReportDate(long value) {
        
        reportDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  报案日期
       * </pre>
       *
       * <code>optional int64 reportDate = 7;</code>
       */
      public Builder clearReportDate() {
        
        reportDate_ = 0L;
        onChanged();
        return this;
      }

      private long areaId_ ;
      /**
       * <pre>
       *   区域id
       * </pre>
       *
       * <code>optional int64 areaId = 8;</code>
       */
      public long getAreaId() {
        return areaId_;
      }
      /**
       * <pre>
       *   区域id
       * </pre>
       *
       * <code>optional int64 areaId = 8;</code>
       */
      public Builder setAreaId(long value) {
        
        areaId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *   区域id
       * </pre>
       *
       * <code>optional int64 areaId = 8;</code>
       */
      public Builder clearAreaId() {
        
        areaId_ = 0L;
        onChanged();
        return this;
      }

      private Object lostAddress_ = "";
      /**
       * <pre>
       *  车辆丢失地址
       * </pre>
       *
       * <code>optional string lostAddress = 9;</code>
       */
      public String getLostAddress() {
        Object ref = lostAddress_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          lostAddress_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *  车辆丢失地址
       * </pre>
       *
       * <code>optional string lostAddress = 9;</code>
       */
      public com.google.protobuf.ByteString
          getLostAddressBytes() {
        Object ref = lostAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          lostAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  车辆丢失地址
       * </pre>
       *
       * <code>optional string lostAddress = 9;</code>
       */
      public Builder setLostAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lostAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  车辆丢失地址
       * </pre>
       *
       * <code>optional string lostAddress = 9;</code>
       */
      public Builder clearLostAddress() {
        
        lostAddress_ = getDefaultInstance().getLostAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  车辆丢失地址
       * </pre>
       *
       * <code>optional string lostAddress = 9;</code>
       */
      public Builder setLostAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lostAddress_ = value;
        onChanged();
        return this;
      }

      private long lostTime_ ;
      /**
       * <pre>
       *   车辆丢失时间
       * </pre>
       *
       * <code>optional int64 lostTime = 10;</code>
       */
      public long getLostTime() {
        return lostTime_;
      }
      /**
       * <pre>
       *   车辆丢失时间
       * </pre>
       *
       * <code>optional int64 lostTime = 10;</code>
       */
      public Builder setLostTime(long value) {
        
        lostTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *   车辆丢失时间
       * </pre>
       *
       * <code>optional int64 lostTime = 10;</code>
       */
      public Builder clearLostTime() {
        
        lostTime_ = 0L;
        onChanged();
        return this;
      }

      private Object lostDescription_ = "";
      /**
       * <pre>
       *   丢失描述
       * </pre>
       *
       * <code>optional string lostDescription = 11;</code>
       */
      public String getLostDescription() {
        Object ref = lostDescription_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          lostDescription_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *   丢失描述
       * </pre>
       *
       * <code>optional string lostDescription = 11;</code>
       */
      public com.google.protobuf.ByteString
          getLostDescriptionBytes() {
        Object ref = lostDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          lostDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *   丢失描述
       * </pre>
       *
       * <code>optional string lostDescription = 11;</code>
       */
      public Builder setLostDescription(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lostDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *   丢失描述
       * </pre>
       *
       * <code>optional string lostDescription = 11;</code>
       */
      public Builder clearLostDescription() {
        
        lostDescription_ = getDefaultInstance().getLostDescription();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *   丢失描述
       * </pre>
       *
       * <code>optional string lostDescription = 11;</code>
       */
      public Builder setLostDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lostDescription_ = value;
        onChanged();
        return this;
      }

      private Object rejectReason_ = "";
      /**
       * <pre>
       *   拒绝原因
       * </pre>
       *
       * <code>optional string rejectReason = 12;</code>
       */
      public String getRejectReason() {
        Object ref = rejectReason_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          rejectReason_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *   拒绝原因
       * </pre>
       *
       * <code>optional string rejectReason = 12;</code>
       */
      public com.google.protobuf.ByteString
          getRejectReasonBytes() {
        Object ref = rejectReason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          rejectReason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *   拒绝原因
       * </pre>
       *
       * <code>optional string rejectReason = 12;</code>
       */
      public Builder setRejectReason(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rejectReason_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *   拒绝原因
       * </pre>
       *
       * <code>optional string rejectReason = 12;</code>
       */
      public Builder clearRejectReason() {
        
        rejectReason_ = getDefaultInstance().getRejectReason();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *   拒绝原因
       * </pre>
       *
       * <code>optional string rejectReason = 12;</code>
       */
      public Builder setRejectReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rejectReason_ = value;
        onChanged();
        return this;
      }

      private Object status_ = "";
      /**
       * <pre>
       * 状态：0.申请丢失1.审核通过 ，2. 申请丢失驳回，3.已找回 4.已丢失，启动索赔（申请丢失后10天，天数待定）
       * </pre>
       *
       * <code>optional string status = 13;</code>
       */
      public String getStatus() {
        Object ref = status_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 状态：0.申请丢失1.审核通过 ，2. 申请丢失驳回，3.已找回 4.已丢失，启动索赔（申请丢失后10天，天数待定）
       * </pre>
       *
       * <code>optional string status = 13;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 状态：0.申请丢失1.审核通过 ，2. 申请丢失驳回，3.已找回 4.已丢失，启动索赔（申请丢失后10天，天数待定）
       * </pre>
       *
       * <code>optional string status = 13;</code>
       */
      public Builder setStatus(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态：0.申请丢失1.审核通过 ，2. 申请丢失驳回，3.已找回 4.已丢失，启动索赔（申请丢失后10天，天数待定）
       * </pre>
       *
       * <code>optional string status = 13;</code>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态：0.申请丢失1.审核通过 ，2. 申请丢失驳回，3.已找回 4.已丢失，启动索赔（申请丢失后10天，天数待定）
       * </pre>
       *
       * <code>optional string status = 13;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }

      private Object createBy_ = "";
      /**
       * <pre>
       *  创建者
       * </pre>
       *
       * <code>optional string createBy = 14;</code>
       */
      public String getCreateBy() {
        Object ref = createBy_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          createBy_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *  创建者
       * </pre>
       *
       * <code>optional string createBy = 14;</code>
       */
      public com.google.protobuf.ByteString
          getCreateByBytes() {
        Object ref = createBy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          createBy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  创建者
       * </pre>
       *
       * <code>optional string createBy = 14;</code>
       */
      public Builder setCreateBy(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        createBy_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  创建者
       * </pre>
       *
       * <code>optional string createBy = 14;</code>
       */
      public Builder clearCreateBy() {
        
        createBy_ = getDefaultInstance().getCreateBy();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  创建者
       * </pre>
       *
       * <code>optional string createBy = 14;</code>
       */
      public Builder setCreateByBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        createBy_ = value;
        onChanged();
        return this;
      }

      private long createDate_ ;
      /**
       * <pre>
       *  创建时间
       * </pre>
       *
       * <code>optional int64 createDate = 15;</code>
       */
      public long getCreateDate() {
        return createDate_;
      }
      /**
       * <pre>
       *  创建时间
       * </pre>
       *
       * <code>optional int64 createDate = 15;</code>
       */
      public Builder setCreateDate(long value) {
        
        createDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  创建时间
       * </pre>
       *
       * <code>optional int64 createDate = 15;</code>
       */
      public Builder clearCreateDate() {
        
        createDate_ = 0L;
        onChanged();
        return this;
      }

      private Object updateBy_ = "";
      /**
       * <pre>
       *  更新者
       * </pre>
       *
       * <code>optional string updateBy = 16;</code>
       */
      public String getUpdateBy() {
        Object ref = updateBy_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          updateBy_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *  更新者
       * </pre>
       *
       * <code>optional string updateBy = 16;</code>
       */
      public com.google.protobuf.ByteString
          getUpdateByBytes() {
        Object ref = updateBy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          updateBy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  更新者
       * </pre>
       *
       * <code>optional string updateBy = 16;</code>
       */
      public Builder setUpdateBy(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        updateBy_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  更新者
       * </pre>
       *
       * <code>optional string updateBy = 16;</code>
       */
      public Builder clearUpdateBy() {
        
        updateBy_ = getDefaultInstance().getUpdateBy();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  更新者
       * </pre>
       *
       * <code>optional string updateBy = 16;</code>
       */
      public Builder setUpdateByBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        updateBy_ = value;
        onChanged();
        return this;
      }

      private long updateDate_ ;
      /**
       * <pre>
       *  更新时间
       * </pre>
       *
       * <code>optional int64 updateDate = 17;</code>
       */
      public long getUpdateDate() {
        return updateDate_;
      }
      /**
       * <pre>
       *  更新时间
       * </pre>
       *
       * <code>optional int64 updateDate = 17;</code>
       */
      public Builder setUpdateDate(long value) {
        
        updateDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  更新时间
       * </pre>
       *
       * <code>optional int64 updateDate = 17;</code>
       */
      public Builder clearUpdateDate() {
        
        updateDate_ = 0L;
        onChanged();
        return this;
      }

      private long companyId_ ;
      /**
       * <pre>
       * 公司id
       * </pre>
       *
       * <code>optional int64 companyId = 18;</code>
       */
      public long getCompanyId() {
        return companyId_;
      }
      /**
       * <pre>
       * 公司id
       * </pre>
       *
       * <code>optional int64 companyId = 18;</code>
       */
      public Builder setCompanyId(long value) {
        
        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 公司id
       * </pre>
       *
       * <code>optional int64 companyId = 18;</code>
       */
      public Builder clearCompanyId() {
        
        companyId_ = 0L;
        onChanged();
        return this;
      }

      private Object delFlag_ = "";
      /**
       * <pre>
       *删除标志
       * </pre>
       *
       * <code>optional string delFlag = 19;</code>
       */
      public String getDelFlag() {
        Object ref = delFlag_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          delFlag_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *删除标志
       * </pre>
       *
       * <code>optional string delFlag = 19;</code>
       */
      public com.google.protobuf.ByteString
          getDelFlagBytes() {
        Object ref = delFlag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          delFlag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *删除标志
       * </pre>
       *
       * <code>optional string delFlag = 19;</code>
       */
      public Builder setDelFlag(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        delFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *删除标志
       * </pre>
       *
       * <code>optional string delFlag = 19;</code>
       */
      public Builder clearDelFlag() {
        
        delFlag_ = getDefaultInstance().getDelFlag();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *删除标志
       * </pre>
       *
       * <code>optional string delFlag = 19;</code>
       */
      public Builder setDelFlagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        delFlag_ = value;
        onChanged();
        return this;
      }

      private Object cardNo_ = "";
      /**
       * <pre>
       * 卡号
       * </pre>
       *
       * <code>optional string cardNo = 20;</code>
       */
      public String getCardNo() {
        Object ref = cardNo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          cardNo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 卡号
       * </pre>
       *
       * <code>optional string cardNo = 20;</code>
       */
      public com.google.protobuf.ByteString
          getCardNoBytes() {
        Object ref = cardNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cardNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 卡号
       * </pre>
       *
       * <code>optional string cardNo = 20;</code>
       */
      public Builder setCardNo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cardNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 卡号
       * </pre>
       *
       * <code>optional string cardNo = 20;</code>
       */
      public Builder clearCardNo() {
        
        cardNo_ = getDefaultInstance().getCardNo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 卡号
       * </pre>
       *
       * <code>optional string cardNo = 20;</code>
       */
      public Builder setCardNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cardNo_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:BikeLostMessage)
    }

    // @@protoc_insertion_point(class_scope:BikeLostMessage)
    private static final com.yzh.rfid.app.response.BikeLost.BikeLostMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.response.BikeLost.BikeLostMessage();
    }

    public static com.yzh.rfid.app.response.BikeLost.BikeLostMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BikeLostMessage>
        PARSER = new com.google.protobuf.AbstractParser<BikeLostMessage>() {
      public BikeLostMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BikeLostMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BikeLostMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BikeLostMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.response.BikeLost.BikeLostMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BikeLostMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BikeLostMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016BikeLost.proto\"\202\003\n\017BikeLostMessage\022\n\n\002" +
      "id\030\001 \001(\003\022\016\n\006userId\030\002 \001(\003\022\020\n\010userName\030\003 \001" +
      "(\t\022\022\n\nuserIdCard\030\004 \001(\t\022\016\n\006bikeId\030\005 \001(\003\022\023" +
      "\n\013plateNumber\030\006 \001(\t\022\022\n\nreportDate\030\007 \001(\003\022" +
      "\016\n\006areaId\030\010 \001(\003\022\023\n\013lostAddress\030\t \001(\t\022\020\n\010" +
      "lostTime\030\n \001(\003\022\027\n\017lostDescription\030\013 \001(\t\022" +
      "\024\n\014rejectReason\030\014 \001(\t\022\016\n\006status\030\r \001(\t\022\020\n" +
      "\010createBy\030\016 \001(\t\022\022\n\ncreateDate\030\017 \001(\003\022\020\n\010u" +
      "pdateBy\030\020 \001(\t\022\022\n\nupdateDate\030\021 \001(\003\022\021\n\tcom" +
      "panyId\030\022 \001(\003\022\017\n\007delFlag\030\023 \001(\t\022\016\n\006cardNo\030",
      "\024 \001(\tB)\n\035com.yzh.rfid.app.responseB\010" +
      "BikeLostb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BikeLostMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BikeLostMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BikeLostMessage_descriptor,
        new String[] { "Id", "UserId", "UserName", "UserIdCard", "BikeId", "PlateNumber", "ReportDate", "AreaId", "LostAddress", "LostTime", "LostDescription", "RejectReason", "Status", "CreateBy", "CreateDate", "UpdateBy", "UpdateDate", "CompanyId", "DelFlag", "CardNo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
