// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetBikeLostResponse.proto

package com.yzh.rfid.app.response;

public final class GetBikeLostResponse {
  private GetBikeLostResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetBikeLostResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetBikeLostResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>repeated .BikeLostMessage bikeLost = 2;</code>
     */
    java.util.List<com.yzh.rfid.app.response.BikeLost.BikeLostMessage> 
        getBikeLostList();
    /**
     * <code>repeated .BikeLostMessage bikeLost = 2;</code>
     */
    com.yzh.rfid.app.response.BikeLost.BikeLostMessage getBikeLost(int index);
    /**
     * <code>repeated .BikeLostMessage bikeLost = 2;</code>
     */
    int getBikeLostCount();
    /**
     * <code>repeated .BikeLostMessage bikeLost = 2;</code>
     */
    java.util.List<? extends com.yzh.rfid.app.response.BikeLost.BikeLostMessageOrBuilder> 
        getBikeLostOrBuilderList();
    /**
     * <code>repeated .BikeLostMessage bikeLost = 2;</code>
     */
    com.yzh.rfid.app.response.BikeLost.BikeLostMessageOrBuilder getBikeLostOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code GetBikeLostResponseMessage}
   */
  public  static final class GetBikeLostResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetBikeLostResponseMessage)
      GetBikeLostResponseMessageOrBuilder {
    // Use GetBikeLostResponseMessage.newBuilder() to construct.
    private GetBikeLostResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetBikeLostResponseMessage() {
      bikeLost_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetBikeLostResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                bikeLost_ = new java.util.ArrayList<com.yzh.rfid.app.response.BikeLost.BikeLostMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              bikeLost_.add(
                  input.readMessage(com.yzh.rfid.app.response.BikeLost.BikeLostMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          bikeLost_ = java.util.Collections.unmodifiableList(bikeLost_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.response.GetBikeLostResponse.internal_static_GetBikeLostResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.response.GetBikeLostResponse.internal_static_GetBikeLostResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage.class, com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int BIKELOST_FIELD_NUMBER = 2;
    private java.util.List<com.yzh.rfid.app.response.BikeLost.BikeLostMessage> bikeLost_;
    /**
     * <code>repeated .BikeLostMessage bikeLost = 2;</code>
     */
    public java.util.List<com.yzh.rfid.app.response.BikeLost.BikeLostMessage> getBikeLostList() {
      return bikeLost_;
    }
    /**
     * <code>repeated .BikeLostMessage bikeLost = 2;</code>
     */
    public java.util.List<? extends com.yzh.rfid.app.response.BikeLost.BikeLostMessageOrBuilder> 
        getBikeLostOrBuilderList() {
      return bikeLost_;
    }
    /**
     * <code>repeated .BikeLostMessage bikeLost = 2;</code>
     */
    public int getBikeLostCount() {
      return bikeLost_.size();
    }
    /**
     * <code>repeated .BikeLostMessage bikeLost = 2;</code>
     */
    public com.yzh.rfid.app.response.BikeLost.BikeLostMessage getBikeLost(int index) {
      return bikeLost_.get(index);
    }
    /**
     * <code>repeated .BikeLostMessage bikeLost = 2;</code>
     */
    public com.yzh.rfid.app.response.BikeLost.BikeLostMessageOrBuilder getBikeLostOrBuilder(
        int index) {
      return bikeLost_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      for (int i = 0; i < bikeLost_.size(); i++) {
        output.writeMessage(2, bikeLost_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      for (int i = 0; i < bikeLost_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, bikeLost_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage other = (com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && getBikeLostList()
          .equals(other.getBikeLostList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      if (getBikeLostCount() > 0) {
        hash = (37 * hash) + BIKELOST_FIELD_NUMBER;
        hash = (53 * hash) + getBikeLostList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetBikeLostResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetBikeLostResponseMessage)
        com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.response.GetBikeLostResponse.internal_static_GetBikeLostResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.response.GetBikeLostResponse.internal_static_GetBikeLostResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage.class, com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBikeLostFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        if (bikeLostBuilder_ == null) {
          bikeLost_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          bikeLostBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.response.GetBikeLostResponse.internal_static_GetBikeLostResponseMessage_descriptor;
      }

      public com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage build() {
        com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage buildPartial() {
        com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage result = new com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        if (bikeLostBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            bikeLost_ = java.util.Collections.unmodifiableList(bikeLost_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.bikeLost_ = bikeLost_;
        } else {
          result.bikeLost_ = bikeLostBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage) {
          return mergeFrom((com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage other) {
        if (other == com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (bikeLostBuilder_ == null) {
          if (!other.bikeLost_.isEmpty()) {
            if (bikeLost_.isEmpty()) {
              bikeLost_ = other.bikeLost_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBikeLostIsMutable();
              bikeLost_.addAll(other.bikeLost_);
            }
            onChanged();
          }
        } else {
          if (!other.bikeLost_.isEmpty()) {
            if (bikeLostBuilder_.isEmpty()) {
              bikeLostBuilder_.dispose();
              bikeLostBuilder_ = null;
              bikeLost_ = other.bikeLost_;
              bitField0_ = (bitField0_ & ~0x00000002);
              bikeLostBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBikeLostFieldBuilder() : null;
            } else {
              bikeLostBuilder_.addAllMessages(other.bikeLost_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> 
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private java.util.List<com.yzh.rfid.app.response.BikeLost.BikeLostMessage> bikeLost_ =
        java.util.Collections.emptyList();
      private void ensureBikeLostIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          bikeLost_ = new java.util.ArrayList<com.yzh.rfid.app.response.BikeLost.BikeLostMessage>(bikeLost_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.BikeLost.BikeLostMessage, com.yzh.rfid.app.response.BikeLost.BikeLostMessage.Builder, com.yzh.rfid.app.response.BikeLost.BikeLostMessageOrBuilder> bikeLostBuilder_;

      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.BikeLost.BikeLostMessage> getBikeLostList() {
        if (bikeLostBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bikeLost_);
        } else {
          return bikeLostBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public int getBikeLostCount() {
        if (bikeLostBuilder_ == null) {
          return bikeLost_.size();
        } else {
          return bikeLostBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public com.yzh.rfid.app.response.BikeLost.BikeLostMessage getBikeLost(int index) {
        if (bikeLostBuilder_ == null) {
          return bikeLost_.get(index);
        } else {
          return bikeLostBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public Builder setBikeLost(
          int index, com.yzh.rfid.app.response.BikeLost.BikeLostMessage value) {
        if (bikeLostBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBikeLostIsMutable();
          bikeLost_.set(index, value);
          onChanged();
        } else {
          bikeLostBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public Builder setBikeLost(
          int index, com.yzh.rfid.app.response.BikeLost.BikeLostMessage.Builder builderForValue) {
        if (bikeLostBuilder_ == null) {
          ensureBikeLostIsMutable();
          bikeLost_.set(index, builderForValue.build());
          onChanged();
        } else {
          bikeLostBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public Builder addBikeLost(com.yzh.rfid.app.response.BikeLost.BikeLostMessage value) {
        if (bikeLostBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBikeLostIsMutable();
          bikeLost_.add(value);
          onChanged();
        } else {
          bikeLostBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public Builder addBikeLost(
          int index, com.yzh.rfid.app.response.BikeLost.BikeLostMessage value) {
        if (bikeLostBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBikeLostIsMutable();
          bikeLost_.add(index, value);
          onChanged();
        } else {
          bikeLostBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public Builder addBikeLost(
          com.yzh.rfid.app.response.BikeLost.BikeLostMessage.Builder builderForValue) {
        if (bikeLostBuilder_ == null) {
          ensureBikeLostIsMutable();
          bikeLost_.add(builderForValue.build());
          onChanged();
        } else {
          bikeLostBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public Builder addBikeLost(
          int index, com.yzh.rfid.app.response.BikeLost.BikeLostMessage.Builder builderForValue) {
        if (bikeLostBuilder_ == null) {
          ensureBikeLostIsMutable();
          bikeLost_.add(index, builderForValue.build());
          onChanged();
        } else {
          bikeLostBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public Builder addAllBikeLost(
          Iterable<? extends com.yzh.rfid.app.response.BikeLost.BikeLostMessage> values) {
        if (bikeLostBuilder_ == null) {
          ensureBikeLostIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, bikeLost_);
          onChanged();
        } else {
          bikeLostBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public Builder clearBikeLost() {
        if (bikeLostBuilder_ == null) {
          bikeLost_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          bikeLostBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public Builder removeBikeLost(int index) {
        if (bikeLostBuilder_ == null) {
          ensureBikeLostIsMutable();
          bikeLost_.remove(index);
          onChanged();
        } else {
          bikeLostBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public com.yzh.rfid.app.response.BikeLost.BikeLostMessage.Builder getBikeLostBuilder(
          int index) {
        return getBikeLostFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public com.yzh.rfid.app.response.BikeLost.BikeLostMessageOrBuilder getBikeLostOrBuilder(
          int index) {
        if (bikeLostBuilder_ == null) {
          return bikeLost_.get(index);  } else {
          return bikeLostBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public java.util.List<? extends com.yzh.rfid.app.response.BikeLost.BikeLostMessageOrBuilder> 
           getBikeLostOrBuilderList() {
        if (bikeLostBuilder_ != null) {
          return bikeLostBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bikeLost_);
        }
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public com.yzh.rfid.app.response.BikeLost.BikeLostMessage.Builder addBikeLostBuilder() {
        return getBikeLostFieldBuilder().addBuilder(
            com.yzh.rfid.app.response.BikeLost.BikeLostMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public com.yzh.rfid.app.response.BikeLost.BikeLostMessage.Builder addBikeLostBuilder(
          int index) {
        return getBikeLostFieldBuilder().addBuilder(
            index, com.yzh.rfid.app.response.BikeLost.BikeLostMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .BikeLostMessage bikeLost = 2;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.BikeLost.BikeLostMessage.Builder> 
           getBikeLostBuilderList() {
        return getBikeLostFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.BikeLost.BikeLostMessage, com.yzh.rfid.app.response.BikeLost.BikeLostMessage.Builder, com.yzh.rfid.app.response.BikeLost.BikeLostMessageOrBuilder> 
          getBikeLostFieldBuilder() {
        if (bikeLostBuilder_ == null) {
          bikeLostBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yzh.rfid.app.response.BikeLost.BikeLostMessage, com.yzh.rfid.app.response.BikeLost.BikeLostMessage.Builder, com.yzh.rfid.app.response.BikeLost.BikeLostMessageOrBuilder>(
                  bikeLost_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          bikeLost_ = null;
        }
        return bikeLostBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetBikeLostResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:GetBikeLostResponseMessage)
    private static final com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage();
    }

    public static com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetBikeLostResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetBikeLostResponseMessage>() {
      public GetBikeLostResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetBikeLostResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetBikeLostResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetBikeLostResponseMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.response.GetBikeLostResponse.GetBikeLostResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetBikeLostResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetBikeLostResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031GetBikeLostResponse.proto\032\032ErrorMessag" +
      "eResponse.proto\032\016BikeLost.proto\"a\n\032GetBi" +
      "keLostResponseMessage\022\037\n\010errorMsg\030\001 \001(\0132" +
      "\r.ErrorMessage\022\"\n\010bikeLost\030\002 \003(\0132\020.BikeL" +
      "ostMessageB4\n\035com.yzh.rfid.app.respo" +
      "nseB\023GetBikeLostResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor(),
          com.yzh.rfid.app.response.BikeLost.getDescriptor(),
        }, assigner);
    internal_static_GetBikeLostResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetBikeLostResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetBikeLostResponseMessage_descriptor,
        new String[] { "ErrorMsg", "BikeLost", });
    com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor();
    com.yzh.rfid.app.response.BikeLost.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
