// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetBikeUserResponse.proto

package com.yzh.rfid.app.response;

public final class GetBikUserResponse {
  private GetBikUserResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetBikeUserResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetBikeUserResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
     */
    java.util.List<com.yzh.rfid.app.response.BikeUser.BikeUserMessage> 
        getBikeUserMessageList();
    /**
     * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
     */
    com.yzh.rfid.app.response.BikeUser.BikeUserMessage getBikeUserMessage(int index);
    /**
     * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
     */
    int getBikeUserMessageCount();
    /**
     * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
     */
    java.util.List<? extends com.yzh.rfid.app.response.BikeUser.BikeUserMessageOrBuilder> 
        getBikeUserMessageOrBuilderList();
    /**
     * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
     */
    com.yzh.rfid.app.response.BikeUser.BikeUserMessageOrBuilder getBikeUserMessageOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code GetBikeUserResponseMessage}
   */
  public  static final class GetBikeUserResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetBikeUserResponseMessage)
      GetBikeUserResponseMessageOrBuilder {
    // Use GetBikeUserResponseMessage.newBuilder() to construct.
    private GetBikeUserResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetBikeUserResponseMessage() {
      bikeUserMessage_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetBikeUserResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                bikeUserMessage_ = new java.util.ArrayList<com.yzh.rfid.app.response.BikeUser.BikeUserMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              bikeUserMessage_.add(
                  input.readMessage(com.yzh.rfid.app.response.BikeUser.BikeUserMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          bikeUserMessage_ = java.util.Collections.unmodifiableList(bikeUserMessage_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.response.GetBikUserResponse.internal_static_GetBikeUserResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.response.GetBikUserResponse.internal_static_GetBikeUserResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage.class, com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int BIKEUSERMESSAGE_FIELD_NUMBER = 2;
    private java.util.List<com.yzh.rfid.app.response.BikeUser.BikeUserMessage> bikeUserMessage_;
    /**
     * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
     */
    public java.util.List<com.yzh.rfid.app.response.BikeUser.BikeUserMessage> getBikeUserMessageList() {
      return bikeUserMessage_;
    }
    /**
     * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
     */
    public java.util.List<? extends com.yzh.rfid.app.response.BikeUser.BikeUserMessageOrBuilder> 
        getBikeUserMessageOrBuilderList() {
      return bikeUserMessage_;
    }
    /**
     * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
     */
    public int getBikeUserMessageCount() {
      return bikeUserMessage_.size();
    }
    /**
     * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
     */
    public com.yzh.rfid.app.response.BikeUser.BikeUserMessage getBikeUserMessage(int index) {
      return bikeUserMessage_.get(index);
    }
    /**
     * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
     */
    public com.yzh.rfid.app.response.BikeUser.BikeUserMessageOrBuilder getBikeUserMessageOrBuilder(
        int index) {
      return bikeUserMessage_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      for (int i = 0; i < bikeUserMessage_.size(); i++) {
        output.writeMessage(2, bikeUserMessage_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      for (int i = 0; i < bikeUserMessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, bikeUserMessage_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage other = (com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && getBikeUserMessageList()
          .equals(other.getBikeUserMessageList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      if (getBikeUserMessageCount() > 0) {
        hash = (37 * hash) + BIKEUSERMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getBikeUserMessageList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetBikeUserResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetBikeUserResponseMessage)
        com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.response.GetBikUserResponse.internal_static_GetBikeUserResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.response.GetBikUserResponse.internal_static_GetBikeUserResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage.class, com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBikeUserMessageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        if (bikeUserMessageBuilder_ == null) {
          bikeUserMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          bikeUserMessageBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.response.GetBikUserResponse.internal_static_GetBikeUserResponseMessage_descriptor;
      }

      public com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage build() {
        com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage buildPartial() {
        com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage result = new com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        if (bikeUserMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            bikeUserMessage_ = java.util.Collections.unmodifiableList(bikeUserMessage_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.bikeUserMessage_ = bikeUserMessage_;
        } else {
          result.bikeUserMessage_ = bikeUserMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage) {
          return mergeFrom((com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage other) {
        if (other == com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (bikeUserMessageBuilder_ == null) {
          if (!other.bikeUserMessage_.isEmpty()) {
            if (bikeUserMessage_.isEmpty()) {
              bikeUserMessage_ = other.bikeUserMessage_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBikeUserMessageIsMutable();
              bikeUserMessage_.addAll(other.bikeUserMessage_);
            }
            onChanged();
          }
        } else {
          if (!other.bikeUserMessage_.isEmpty()) {
            if (bikeUserMessageBuilder_.isEmpty()) {
              bikeUserMessageBuilder_.dispose();
              bikeUserMessageBuilder_ = null;
              bikeUserMessage_ = other.bikeUserMessage_;
              bitField0_ = (bitField0_ & ~0x00000002);
              bikeUserMessageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBikeUserMessageFieldBuilder() : null;
            } else {
              bikeUserMessageBuilder_.addAllMessages(other.bikeUserMessage_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> 
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private java.util.List<com.yzh.rfid.app.response.BikeUser.BikeUserMessage> bikeUserMessage_ =
        java.util.Collections.emptyList();
      private void ensureBikeUserMessageIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          bikeUserMessage_ = new java.util.ArrayList<com.yzh.rfid.app.response.BikeUser.BikeUserMessage>(bikeUserMessage_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.BikeUser.BikeUserMessage, com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder, com.yzh.rfid.app.response.BikeUser.BikeUserMessageOrBuilder> bikeUserMessageBuilder_;

      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.BikeUser.BikeUserMessage> getBikeUserMessageList() {
        if (bikeUserMessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bikeUserMessage_);
        } else {
          return bikeUserMessageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public int getBikeUserMessageCount() {
        if (bikeUserMessageBuilder_ == null) {
          return bikeUserMessage_.size();
        } else {
          return bikeUserMessageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.BikeUser.BikeUserMessage getBikeUserMessage(int index) {
        if (bikeUserMessageBuilder_ == null) {
          return bikeUserMessage_.get(index);
        } else {
          return bikeUserMessageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public Builder setBikeUserMessage(
          int index, com.yzh.rfid.app.response.BikeUser.BikeUserMessage value) {
        if (bikeUserMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBikeUserMessageIsMutable();
          bikeUserMessage_.set(index, value);
          onChanged();
        } else {
          bikeUserMessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public Builder setBikeUserMessage(
          int index, com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder builderForValue) {
        if (bikeUserMessageBuilder_ == null) {
          ensureBikeUserMessageIsMutable();
          bikeUserMessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          bikeUserMessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public Builder addBikeUserMessage(com.yzh.rfid.app.response.BikeUser.BikeUserMessage value) {
        if (bikeUserMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBikeUserMessageIsMutable();
          bikeUserMessage_.add(value);
          onChanged();
        } else {
          bikeUserMessageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public Builder addBikeUserMessage(
          int index, com.yzh.rfid.app.response.BikeUser.BikeUserMessage value) {
        if (bikeUserMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBikeUserMessageIsMutable();
          bikeUserMessage_.add(index, value);
          onChanged();
        } else {
          bikeUserMessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public Builder addBikeUserMessage(
          com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder builderForValue) {
        if (bikeUserMessageBuilder_ == null) {
          ensureBikeUserMessageIsMutable();
          bikeUserMessage_.add(builderForValue.build());
          onChanged();
        } else {
          bikeUserMessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public Builder addBikeUserMessage(
          int index, com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder builderForValue) {
        if (bikeUserMessageBuilder_ == null) {
          ensureBikeUserMessageIsMutable();
          bikeUserMessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          bikeUserMessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public Builder addAllBikeUserMessage(
          Iterable<? extends com.yzh.rfid.app.response.BikeUser.BikeUserMessage> values) {
        if (bikeUserMessageBuilder_ == null) {
          ensureBikeUserMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, bikeUserMessage_);
          onChanged();
        } else {
          bikeUserMessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public Builder clearBikeUserMessage() {
        if (bikeUserMessageBuilder_ == null) {
          bikeUserMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          bikeUserMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public Builder removeBikeUserMessage(int index) {
        if (bikeUserMessageBuilder_ == null) {
          ensureBikeUserMessageIsMutable();
          bikeUserMessage_.remove(index);
          onChanged();
        } else {
          bikeUserMessageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder getBikeUserMessageBuilder(
          int index) {
        return getBikeUserMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.BikeUser.BikeUserMessageOrBuilder getBikeUserMessageOrBuilder(
          int index) {
        if (bikeUserMessageBuilder_ == null) {
          return bikeUserMessage_.get(index);  } else {
          return bikeUserMessageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public java.util.List<? extends com.yzh.rfid.app.response.BikeUser.BikeUserMessageOrBuilder> 
           getBikeUserMessageOrBuilderList() {
        if (bikeUserMessageBuilder_ != null) {
          return bikeUserMessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bikeUserMessage_);
        }
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder addBikeUserMessageBuilder() {
        return getBikeUserMessageFieldBuilder().addBuilder(
            com.yzh.rfid.app.response.BikeUser.BikeUserMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder addBikeUserMessageBuilder(
          int index) {
        return getBikeUserMessageFieldBuilder().addBuilder(
            index, com.yzh.rfid.app.response.BikeUser.BikeUserMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .BikeUserMessage bikeUserMessage = 2;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder> 
           getBikeUserMessageBuilderList() {
        return getBikeUserMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.BikeUser.BikeUserMessage, com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder, com.yzh.rfid.app.response.BikeUser.BikeUserMessageOrBuilder> 
          getBikeUserMessageFieldBuilder() {
        if (bikeUserMessageBuilder_ == null) {
          bikeUserMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yzh.rfid.app.response.BikeUser.BikeUserMessage, com.yzh.rfid.app.response.BikeUser.BikeUserMessage.Builder, com.yzh.rfid.app.response.BikeUser.BikeUserMessageOrBuilder>(
                  bikeUserMessage_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          bikeUserMessage_ = null;
        }
        return bikeUserMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetBikeUserResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:GetBikeUserResponseMessage)
    private static final com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage();
    }

    public static com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetBikeUserResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetBikeUserResponseMessage>() {
      public GetBikeUserResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetBikeUserResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetBikeUserResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetBikeUserResponseMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.response.GetBikUserResponse.GetBikeUserResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetBikeUserResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetBikeUserResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031GetBikeUserResponse.proto\032\032ErrorMessag" +
      "eResponse.proto\032\016BikeUser.proto\"h\n\032GetBi" +
      "keUserResponseMessage\022\037\n\010errorMsg\030\001 \001(\0132" +
      "\r.ErrorMessage\022)\n\017bikeUserMessage\030\002 \003(\0132" +
      "\020.BikeUserMessageB3\n\035com.yzh.rfid.ap" +
      "p.responseB\022GetBikUserResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor(),
          com.yzh.rfid.app.response.BikeUser.getDescriptor(),
        }, assigner);
    internal_static_GetBikeUserResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetBikeUserResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetBikeUserResponseMessage_descriptor,
        new String[] { "ErrorMsg", "BikeUserMessage", });
    com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor();
    com.yzh.rfid.app.response.BikeUser.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
