// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetBikesResponse.proto

package com.yzh.rfid.app.response;

public final class GetBikesResponse {
  private GetBikesResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetBikesResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetBikesResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>repeated .BikeMessage bike = 2;</code>
     */
    java.util.List<com.yzh.rfid.app.response.Bike.BikeMessage> 
        getBikeList();
    /**
     * <code>repeated .BikeMessage bike = 2;</code>
     */
    com.yzh.rfid.app.response.Bike.BikeMessage getBike(int index);
    /**
     * <code>repeated .BikeMessage bike = 2;</code>
     */
    int getBikeCount();
    /**
     * <code>repeated .BikeMessage bike = 2;</code>
     */
    java.util.List<? extends com.yzh.rfid.app.response.Bike.BikeMessageOrBuilder> 
        getBikeOrBuilderList();
    /**
     * <code>repeated .BikeMessage bike = 2;</code>
     */
    com.yzh.rfid.app.response.Bike.BikeMessageOrBuilder getBikeOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code GetBikesResponseMessage}
   */
  public  static final class GetBikesResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetBikesResponseMessage)
      GetBikesResponseMessageOrBuilder {
    // Use GetBikesResponseMessage.newBuilder() to construct.
    private GetBikesResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetBikesResponseMessage() {
      bike_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetBikesResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                bike_ = new java.util.ArrayList<com.yzh.rfid.app.response.Bike.BikeMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              bike_.add(
                  input.readMessage(com.yzh.rfid.app.response.Bike.BikeMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          bike_ = java.util.Collections.unmodifiableList(bike_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.response.GetBikesResponse.internal_static_GetBikesResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.response.GetBikesResponse.internal_static_GetBikesResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage.class, com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int BIKE_FIELD_NUMBER = 2;
    private java.util.List<com.yzh.rfid.app.response.Bike.BikeMessage> bike_;
    /**
     * <code>repeated .BikeMessage bike = 2;</code>
     */
    public java.util.List<com.yzh.rfid.app.response.Bike.BikeMessage> getBikeList() {
      return bike_;
    }
    /**
     * <code>repeated .BikeMessage bike = 2;</code>
     */
    public java.util.List<? extends com.yzh.rfid.app.response.Bike.BikeMessageOrBuilder> 
        getBikeOrBuilderList() {
      return bike_;
    }
    /**
     * <code>repeated .BikeMessage bike = 2;</code>
     */
    public int getBikeCount() {
      return bike_.size();
    }
    /**
     * <code>repeated .BikeMessage bike = 2;</code>
     */
    public com.yzh.rfid.app.response.Bike.BikeMessage getBike(int index) {
      return bike_.get(index);
    }
    /**
     * <code>repeated .BikeMessage bike = 2;</code>
     */
    public com.yzh.rfid.app.response.Bike.BikeMessageOrBuilder getBikeOrBuilder(
        int index) {
      return bike_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      for (int i = 0; i < bike_.size(); i++) {
        output.writeMessage(2, bike_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      for (int i = 0; i < bike_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, bike_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage other = (com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && getBikeList()
          .equals(other.getBikeList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      if (getBikeCount() > 0) {
        hash = (37 * hash) + BIKE_FIELD_NUMBER;
        hash = (53 * hash) + getBikeList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetBikesResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetBikesResponseMessage)
        com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.response.GetBikesResponse.internal_static_GetBikesResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.response.GetBikesResponse.internal_static_GetBikesResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage.class, com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBikeFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        if (bikeBuilder_ == null) {
          bike_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          bikeBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.response.GetBikesResponse.internal_static_GetBikesResponseMessage_descriptor;
      }

      public com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage build() {
        com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage buildPartial() {
        com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage result = new com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        if (bikeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            bike_ = java.util.Collections.unmodifiableList(bike_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.bike_ = bike_;
        } else {
          result.bike_ = bikeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage) {
          return mergeFrom((com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage other) {
        if (other == com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (bikeBuilder_ == null) {
          if (!other.bike_.isEmpty()) {
            if (bike_.isEmpty()) {
              bike_ = other.bike_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBikeIsMutable();
              bike_.addAll(other.bike_);
            }
            onChanged();
          }
        } else {
          if (!other.bike_.isEmpty()) {
            if (bikeBuilder_.isEmpty()) {
              bikeBuilder_.dispose();
              bikeBuilder_ = null;
              bike_ = other.bike_;
              bitField0_ = (bitField0_ & ~0x00000002);
              bikeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBikeFieldBuilder() : null;
            } else {
              bikeBuilder_.addAllMessages(other.bike_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> 
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private java.util.List<com.yzh.rfid.app.response.Bike.BikeMessage> bike_ =
        java.util.Collections.emptyList();
      private void ensureBikeIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          bike_ = new java.util.ArrayList<com.yzh.rfid.app.response.Bike.BikeMessage>(bike_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.Bike.BikeMessage, com.yzh.rfid.app.response.Bike.BikeMessage.Builder, com.yzh.rfid.app.response.Bike.BikeMessageOrBuilder> bikeBuilder_;

      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.Bike.BikeMessage> getBikeList() {
        if (bikeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bike_);
        } else {
          return bikeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public int getBikeCount() {
        if (bikeBuilder_ == null) {
          return bike_.size();
        } else {
          return bikeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public com.yzh.rfid.app.response.Bike.BikeMessage getBike(int index) {
        if (bikeBuilder_ == null) {
          return bike_.get(index);
        } else {
          return bikeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public Builder setBike(
          int index, com.yzh.rfid.app.response.Bike.BikeMessage value) {
        if (bikeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBikeIsMutable();
          bike_.set(index, value);
          onChanged();
        } else {
          bikeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public Builder setBike(
          int index, com.yzh.rfid.app.response.Bike.BikeMessage.Builder builderForValue) {
        if (bikeBuilder_ == null) {
          ensureBikeIsMutable();
          bike_.set(index, builderForValue.build());
          onChanged();
        } else {
          bikeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public Builder addBike(com.yzh.rfid.app.response.Bike.BikeMessage value) {
        if (bikeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBikeIsMutable();
          bike_.add(value);
          onChanged();
        } else {
          bikeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public Builder addBike(
          int index, com.yzh.rfid.app.response.Bike.BikeMessage value) {
        if (bikeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBikeIsMutable();
          bike_.add(index, value);
          onChanged();
        } else {
          bikeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public Builder addBike(
          com.yzh.rfid.app.response.Bike.BikeMessage.Builder builderForValue) {
        if (bikeBuilder_ == null) {
          ensureBikeIsMutable();
          bike_.add(builderForValue.build());
          onChanged();
        } else {
          bikeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public Builder addBike(
          int index, com.yzh.rfid.app.response.Bike.BikeMessage.Builder builderForValue) {
        if (bikeBuilder_ == null) {
          ensureBikeIsMutable();
          bike_.add(index, builderForValue.build());
          onChanged();
        } else {
          bikeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public Builder addAllBike(
          Iterable<? extends com.yzh.rfid.app.response.Bike.BikeMessage> values) {
        if (bikeBuilder_ == null) {
          ensureBikeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, bike_);
          onChanged();
        } else {
          bikeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public Builder clearBike() {
        if (bikeBuilder_ == null) {
          bike_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          bikeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public Builder removeBike(int index) {
        if (bikeBuilder_ == null) {
          ensureBikeIsMutable();
          bike_.remove(index);
          onChanged();
        } else {
          bikeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public com.yzh.rfid.app.response.Bike.BikeMessage.Builder getBikeBuilder(
          int index) {
        return getBikeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public com.yzh.rfid.app.response.Bike.BikeMessageOrBuilder getBikeOrBuilder(
          int index) {
        if (bikeBuilder_ == null) {
          return bike_.get(index);  } else {
          return bikeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public java.util.List<? extends com.yzh.rfid.app.response.Bike.BikeMessageOrBuilder> 
           getBikeOrBuilderList() {
        if (bikeBuilder_ != null) {
          return bikeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bike_);
        }
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public com.yzh.rfid.app.response.Bike.BikeMessage.Builder addBikeBuilder() {
        return getBikeFieldBuilder().addBuilder(
            com.yzh.rfid.app.response.Bike.BikeMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public com.yzh.rfid.app.response.Bike.BikeMessage.Builder addBikeBuilder(
          int index) {
        return getBikeFieldBuilder().addBuilder(
            index, com.yzh.rfid.app.response.Bike.BikeMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .BikeMessage bike = 2;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.Bike.BikeMessage.Builder> 
           getBikeBuilderList() {
        return getBikeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.Bike.BikeMessage, com.yzh.rfid.app.response.Bike.BikeMessage.Builder, com.yzh.rfid.app.response.Bike.BikeMessageOrBuilder> 
          getBikeFieldBuilder() {
        if (bikeBuilder_ == null) {
          bikeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yzh.rfid.app.response.Bike.BikeMessage, com.yzh.rfid.app.response.Bike.BikeMessage.Builder, com.yzh.rfid.app.response.Bike.BikeMessageOrBuilder>(
                  bike_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          bike_ = null;
        }
        return bikeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetBikesResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:GetBikesResponseMessage)
    private static final com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage();
    }

    public static com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetBikesResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetBikesResponseMessage>() {
      public GetBikesResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetBikesResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetBikesResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetBikesResponseMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.response.GetBikesResponse.GetBikesResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetBikesResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetBikesResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026GetBikesResponse.proto\032\032ErrorMessageRe" +
      "sponse.proto\032\nBike.proto\"V\n\027GetBikesResp" +
      "onseMessage\022\037\n\010errorMsg\030\001 \001(\0132\r.ErrorMes" +
      "sage\022\032\n\004bike\030\002 \003(\0132\014.BikeMessageB1\n\035com." +
      "yzh.rfid.app.responseB\020GetBikesRespo" +
      "nseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor(),
          com.yzh.rfid.app.response.Bike.getDescriptor(),
        }, assigner);
    internal_static_GetBikesResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetBikesResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetBikesResponseMessage_descriptor,
        new String[] { "ErrorMsg", "Bike", });
    com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor();
    com.yzh.rfid.app.response.Bike.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
