// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetInsuranceResponse.proto

package com.yzh.rfid.app.response;

public final class GetInsuranceResponse {
  private GetInsuranceResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetInsuranceResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetInsuranceResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
     */
    java.util.List<com.yzh.rfid.app.response.Insurance.InsuranceMessage> 
        getInsuranceMessageList();
    /**
     * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
     */
    com.yzh.rfid.app.response.Insurance.InsuranceMessage getInsuranceMessage(int index);
    /**
     * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
     */
    int getInsuranceMessageCount();
    /**
     * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
     */
    java.util.List<? extends com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder> 
        getInsuranceMessageOrBuilderList();
    /**
     * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
     */
    com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder getInsuranceMessageOrBuilder(
            int index);
  }
  /**
   * <pre>
   * 公安app
   * </pre>
   *
   * Protobuf type {@code GetInsuranceResponseMessage}
   */
  public  static final class GetInsuranceResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetInsuranceResponseMessage)
      GetInsuranceResponseMessageOrBuilder {
    // Use GetInsuranceResponseMessage.newBuilder() to construct.
    private GetInsuranceResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetInsuranceResponseMessage() {
      insuranceMessage_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetInsuranceResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                insuranceMessage_ = new java.util.ArrayList<com.yzh.rfid.app.response.Insurance.InsuranceMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              insuranceMessage_.add(
                  input.readMessage(com.yzh.rfid.app.response.Insurance.InsuranceMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          insuranceMessage_ = java.util.Collections.unmodifiableList(insuranceMessage_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.response.GetInsuranceResponse.internal_static_GetInsuranceResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.response.GetInsuranceResponse.internal_static_GetInsuranceResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage.class, com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int INSURANCEMESSAGE_FIELD_NUMBER = 2;
    private java.util.List<com.yzh.rfid.app.response.Insurance.InsuranceMessage> insuranceMessage_;
    /**
     * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
     */
    public java.util.List<com.yzh.rfid.app.response.Insurance.InsuranceMessage> getInsuranceMessageList() {
      return insuranceMessage_;
    }
    /**
     * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
     */
    public java.util.List<? extends com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder> 
        getInsuranceMessageOrBuilderList() {
      return insuranceMessage_;
    }
    /**
     * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
     */
    public int getInsuranceMessageCount() {
      return insuranceMessage_.size();
    }
    /**
     * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
     */
    public com.yzh.rfid.app.response.Insurance.InsuranceMessage getInsuranceMessage(int index) {
      return insuranceMessage_.get(index);
    }
    /**
     * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
     */
    public com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder getInsuranceMessageOrBuilder(
        int index) {
      return insuranceMessage_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      for (int i = 0; i < insuranceMessage_.size(); i++) {
        output.writeMessage(2, insuranceMessage_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      for (int i = 0; i < insuranceMessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, insuranceMessage_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage other = (com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && getInsuranceMessageList()
          .equals(other.getInsuranceMessageList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      if (getInsuranceMessageCount() > 0) {
        hash = (37 * hash) + INSURANCEMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getInsuranceMessageList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 公安app
     * </pre>
     *
     * Protobuf type {@code GetInsuranceResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetInsuranceResponseMessage)
        com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.response.GetInsuranceResponse.internal_static_GetInsuranceResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.response.GetInsuranceResponse.internal_static_GetInsuranceResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage.class, com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInsuranceMessageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        if (insuranceMessageBuilder_ == null) {
          insuranceMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          insuranceMessageBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.response.GetInsuranceResponse.internal_static_GetInsuranceResponseMessage_descriptor;
      }

      public com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage build() {
        com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage buildPartial() {
        com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage result = new com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        if (insuranceMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            insuranceMessage_ = java.util.Collections.unmodifiableList(insuranceMessage_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.insuranceMessage_ = insuranceMessage_;
        } else {
          result.insuranceMessage_ = insuranceMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage) {
          return mergeFrom((com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage other) {
        if (other == com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (insuranceMessageBuilder_ == null) {
          if (!other.insuranceMessage_.isEmpty()) {
            if (insuranceMessage_.isEmpty()) {
              insuranceMessage_ = other.insuranceMessage_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureInsuranceMessageIsMutable();
              insuranceMessage_.addAll(other.insuranceMessage_);
            }
            onChanged();
          }
        } else {
          if (!other.insuranceMessage_.isEmpty()) {
            if (insuranceMessageBuilder_.isEmpty()) {
              insuranceMessageBuilder_.dispose();
              insuranceMessageBuilder_ = null;
              insuranceMessage_ = other.insuranceMessage_;
              bitField0_ = (bitField0_ & ~0x00000002);
              insuranceMessageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInsuranceMessageFieldBuilder() : null;
            } else {
              insuranceMessageBuilder_.addAllMessages(other.insuranceMessage_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> 
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private java.util.List<com.yzh.rfid.app.response.Insurance.InsuranceMessage> insuranceMessage_ =
        java.util.Collections.emptyList();
      private void ensureInsuranceMessageIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          insuranceMessage_ = new java.util.ArrayList<com.yzh.rfid.app.response.Insurance.InsuranceMessage>(insuranceMessage_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.Insurance.InsuranceMessage, com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder, com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder> insuranceMessageBuilder_;

      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.Insurance.InsuranceMessage> getInsuranceMessageList() {
        if (insuranceMessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(insuranceMessage_);
        } else {
          return insuranceMessageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public int getInsuranceMessageCount() {
        if (insuranceMessageBuilder_ == null) {
          return insuranceMessage_.size();
        } else {
          return insuranceMessageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.Insurance.InsuranceMessage getInsuranceMessage(int index) {
        if (insuranceMessageBuilder_ == null) {
          return insuranceMessage_.get(index);
        } else {
          return insuranceMessageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public Builder setInsuranceMessage(
          int index, com.yzh.rfid.app.response.Insurance.InsuranceMessage value) {
        if (insuranceMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInsuranceMessageIsMutable();
          insuranceMessage_.set(index, value);
          onChanged();
        } else {
          insuranceMessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public Builder setInsuranceMessage(
          int index, com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder builderForValue) {
        if (insuranceMessageBuilder_ == null) {
          ensureInsuranceMessageIsMutable();
          insuranceMessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          insuranceMessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public Builder addInsuranceMessage(com.yzh.rfid.app.response.Insurance.InsuranceMessage value) {
        if (insuranceMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInsuranceMessageIsMutable();
          insuranceMessage_.add(value);
          onChanged();
        } else {
          insuranceMessageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public Builder addInsuranceMessage(
          int index, com.yzh.rfid.app.response.Insurance.InsuranceMessage value) {
        if (insuranceMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInsuranceMessageIsMutable();
          insuranceMessage_.add(index, value);
          onChanged();
        } else {
          insuranceMessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public Builder addInsuranceMessage(
          com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder builderForValue) {
        if (insuranceMessageBuilder_ == null) {
          ensureInsuranceMessageIsMutable();
          insuranceMessage_.add(builderForValue.build());
          onChanged();
        } else {
          insuranceMessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public Builder addInsuranceMessage(
          int index, com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder builderForValue) {
        if (insuranceMessageBuilder_ == null) {
          ensureInsuranceMessageIsMutable();
          insuranceMessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          insuranceMessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public Builder addAllInsuranceMessage(
          Iterable<? extends com.yzh.rfid.app.response.Insurance.InsuranceMessage> values) {
        if (insuranceMessageBuilder_ == null) {
          ensureInsuranceMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, insuranceMessage_);
          onChanged();
        } else {
          insuranceMessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public Builder clearInsuranceMessage() {
        if (insuranceMessageBuilder_ == null) {
          insuranceMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          insuranceMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public Builder removeInsuranceMessage(int index) {
        if (insuranceMessageBuilder_ == null) {
          ensureInsuranceMessageIsMutable();
          insuranceMessage_.remove(index);
          onChanged();
        } else {
          insuranceMessageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder getInsuranceMessageBuilder(
          int index) {
        return getInsuranceMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder getInsuranceMessageOrBuilder(
          int index) {
        if (insuranceMessageBuilder_ == null) {
          return insuranceMessage_.get(index);  } else {
          return insuranceMessageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public java.util.List<? extends com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder> 
           getInsuranceMessageOrBuilderList() {
        if (insuranceMessageBuilder_ != null) {
          return insuranceMessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(insuranceMessage_);
        }
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder addInsuranceMessageBuilder() {
        return getInsuranceMessageFieldBuilder().addBuilder(
            com.yzh.rfid.app.response.Insurance.InsuranceMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder addInsuranceMessageBuilder(
          int index) {
        return getInsuranceMessageFieldBuilder().addBuilder(
            index, com.yzh.rfid.app.response.Insurance.InsuranceMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .InsuranceMessage insuranceMessage = 2;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder> 
           getInsuranceMessageBuilderList() {
        return getInsuranceMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.Insurance.InsuranceMessage, com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder, com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder> 
          getInsuranceMessageFieldBuilder() {
        if (insuranceMessageBuilder_ == null) {
          insuranceMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yzh.rfid.app.response.Insurance.InsuranceMessage, com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder, com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder>(
                  insuranceMessage_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          insuranceMessage_ = null;
        }
        return insuranceMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetInsuranceResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:GetInsuranceResponseMessage)
    private static final com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage();
    }

    public static com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetInsuranceResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetInsuranceResponseMessage>() {
      public GetInsuranceResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetInsuranceResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetInsuranceResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetInsuranceResponseMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.response.GetInsuranceResponse.GetInsuranceResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetInsuranceResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetInsuranceResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032GetInsuranceResponse.proto\032\032ErrorMessa" +
      "geResponse.proto\032\017Insurance.proto\"k\n\033Get" +
      "InsuranceResponseMessage\022\037\n\010errorMsg\030\001 \001" +
      "(\0132\r.ErrorMessage\022+\n\020insuranceMessage\030\002 " +
      "\003(\0132\021.InsuranceMessageB5\n\035com.yzh.rfidbi" +
      "ke.app.responseB\024GetInsuranceResponseb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor(),
          com.yzh.rfid.app.response.Insurance.getDescriptor(),
        }, assigner);
    internal_static_GetInsuranceResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetInsuranceResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetInsuranceResponseMessage_descriptor,
        new String[] { "ErrorMsg", "InsuranceMessage", });
    com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor();
    com.yzh.rfid.app.response.Insurance.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
