// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetSimpleBikesResponse.proto

package com.yzh.rfid.app.response;

public final class GetSimpleBikesResponse {
  private GetSimpleBikesResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetSimpleBikesResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetSimpleBikesResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>repeated .SimpleBikeMessage bikes = 2;</code>
     */
    java.util.List<com.yzh.rfid.app.response.Bike.SimpleBikeMessage> 
        getBikesList();
    /**
     * <code>repeated .SimpleBikeMessage bikes = 2;</code>
     */
    com.yzh.rfid.app.response.Bike.SimpleBikeMessage getBikes(int index);
    /**
     * <code>repeated .SimpleBikeMessage bikes = 2;</code>
     */
    int getBikesCount();
    /**
     * <code>repeated .SimpleBikeMessage bikes = 2;</code>
     */
    java.util.List<? extends com.yzh.rfid.app.response.Bike.SimpleBikeMessageOrBuilder> 
        getBikesOrBuilderList();
    /**
     * <code>repeated .SimpleBikeMessage bikes = 2;</code>
     */
    com.yzh.rfid.app.response.Bike.SimpleBikeMessageOrBuilder getBikesOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code GetSimpleBikesResponseMessage}
   */
  public  static final class GetSimpleBikesResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetSimpleBikesResponseMessage)
      GetSimpleBikesResponseMessageOrBuilder {
    // Use GetSimpleBikesResponseMessage.newBuilder() to construct.
    private GetSimpleBikesResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetSimpleBikesResponseMessage() {
      bikes_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetSimpleBikesResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                bikes_ = new java.util.ArrayList<com.yzh.rfid.app.response.Bike.SimpleBikeMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              bikes_.add(
                  input.readMessage(com.yzh.rfid.app.response.Bike.SimpleBikeMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          bikes_ = java.util.Collections.unmodifiableList(bikes_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.response.GetSimpleBikesResponse.internal_static_GetSimpleBikesResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.response.GetSimpleBikesResponse.internal_static_GetSimpleBikesResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage.class, com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int BIKES_FIELD_NUMBER = 2;
    private java.util.List<com.yzh.rfid.app.response.Bike.SimpleBikeMessage> bikes_;
    /**
     * <code>repeated .SimpleBikeMessage bikes = 2;</code>
     */
    public java.util.List<com.yzh.rfid.app.response.Bike.SimpleBikeMessage> getBikesList() {
      return bikes_;
    }
    /**
     * <code>repeated .SimpleBikeMessage bikes = 2;</code>
     */
    public java.util.List<? extends com.yzh.rfid.app.response.Bike.SimpleBikeMessageOrBuilder> 
        getBikesOrBuilderList() {
      return bikes_;
    }
    /**
     * <code>repeated .SimpleBikeMessage bikes = 2;</code>
     */
    public int getBikesCount() {
      return bikes_.size();
    }
    /**
     * <code>repeated .SimpleBikeMessage bikes = 2;</code>
     */
    public com.yzh.rfid.app.response.Bike.SimpleBikeMessage getBikes(int index) {
      return bikes_.get(index);
    }
    /**
     * <code>repeated .SimpleBikeMessage bikes = 2;</code>
     */
    public com.yzh.rfid.app.response.Bike.SimpleBikeMessageOrBuilder getBikesOrBuilder(
        int index) {
      return bikes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      for (int i = 0; i < bikes_.size(); i++) {
        output.writeMessage(2, bikes_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      for (int i = 0; i < bikes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, bikes_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage other = (com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && getBikesList()
          .equals(other.getBikesList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      if (getBikesCount() > 0) {
        hash = (37 * hash) + BIKES_FIELD_NUMBER;
        hash = (53 * hash) + getBikesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetSimpleBikesResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetSimpleBikesResponseMessage)
        com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.response.GetSimpleBikesResponse.internal_static_GetSimpleBikesResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.response.GetSimpleBikesResponse.internal_static_GetSimpleBikesResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage.class, com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBikesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        if (bikesBuilder_ == null) {
          bikes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          bikesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.response.GetSimpleBikesResponse.internal_static_GetSimpleBikesResponseMessage_descriptor;
      }

      public com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage build() {
        com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage buildPartial() {
        com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage result = new com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        if (bikesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            bikes_ = java.util.Collections.unmodifiableList(bikes_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.bikes_ = bikes_;
        } else {
          result.bikes_ = bikesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage) {
          return mergeFrom((com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage other) {
        if (other == com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (bikesBuilder_ == null) {
          if (!other.bikes_.isEmpty()) {
            if (bikes_.isEmpty()) {
              bikes_ = other.bikes_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBikesIsMutable();
              bikes_.addAll(other.bikes_);
            }
            onChanged();
          }
        } else {
          if (!other.bikes_.isEmpty()) {
            if (bikesBuilder_.isEmpty()) {
              bikesBuilder_.dispose();
              bikesBuilder_ = null;
              bikes_ = other.bikes_;
              bitField0_ = (bitField0_ & ~0x00000002);
              bikesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBikesFieldBuilder() : null;
            } else {
              bikesBuilder_.addAllMessages(other.bikes_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> 
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private java.util.List<com.yzh.rfid.app.response.Bike.SimpleBikeMessage> bikes_ =
        java.util.Collections.emptyList();
      private void ensureBikesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          bikes_ = new java.util.ArrayList<com.yzh.rfid.app.response.Bike.SimpleBikeMessage>(bikes_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.Bike.SimpleBikeMessage, com.yzh.rfid.app.response.Bike.SimpleBikeMessage.Builder, com.yzh.rfid.app.response.Bike.SimpleBikeMessageOrBuilder> bikesBuilder_;

      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.Bike.SimpleBikeMessage> getBikesList() {
        if (bikesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bikes_);
        } else {
          return bikesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public int getBikesCount() {
        if (bikesBuilder_ == null) {
          return bikes_.size();
        } else {
          return bikesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public com.yzh.rfid.app.response.Bike.SimpleBikeMessage getBikes(int index) {
        if (bikesBuilder_ == null) {
          return bikes_.get(index);
        } else {
          return bikesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public Builder setBikes(
          int index, com.yzh.rfid.app.response.Bike.SimpleBikeMessage value) {
        if (bikesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBikesIsMutable();
          bikes_.set(index, value);
          onChanged();
        } else {
          bikesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public Builder setBikes(
          int index, com.yzh.rfid.app.response.Bike.SimpleBikeMessage.Builder builderForValue) {
        if (bikesBuilder_ == null) {
          ensureBikesIsMutable();
          bikes_.set(index, builderForValue.build());
          onChanged();
        } else {
          bikesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public Builder addBikes(com.yzh.rfid.app.response.Bike.SimpleBikeMessage value) {
        if (bikesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBikesIsMutable();
          bikes_.add(value);
          onChanged();
        } else {
          bikesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public Builder addBikes(
          int index, com.yzh.rfid.app.response.Bike.SimpleBikeMessage value) {
        if (bikesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBikesIsMutable();
          bikes_.add(index, value);
          onChanged();
        } else {
          bikesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public Builder addBikes(
          com.yzh.rfid.app.response.Bike.SimpleBikeMessage.Builder builderForValue) {
        if (bikesBuilder_ == null) {
          ensureBikesIsMutable();
          bikes_.add(builderForValue.build());
          onChanged();
        } else {
          bikesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public Builder addBikes(
          int index, com.yzh.rfid.app.response.Bike.SimpleBikeMessage.Builder builderForValue) {
        if (bikesBuilder_ == null) {
          ensureBikesIsMutable();
          bikes_.add(index, builderForValue.build());
          onChanged();
        } else {
          bikesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public Builder addAllBikes(
          Iterable<? extends com.yzh.rfid.app.response.Bike.SimpleBikeMessage> values) {
        if (bikesBuilder_ == null) {
          ensureBikesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, bikes_);
          onChanged();
        } else {
          bikesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public Builder clearBikes() {
        if (bikesBuilder_ == null) {
          bikes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          bikesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public Builder removeBikes(int index) {
        if (bikesBuilder_ == null) {
          ensureBikesIsMutable();
          bikes_.remove(index);
          onChanged();
        } else {
          bikesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public com.yzh.rfid.app.response.Bike.SimpleBikeMessage.Builder getBikesBuilder(
          int index) {
        return getBikesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public com.yzh.rfid.app.response.Bike.SimpleBikeMessageOrBuilder getBikesOrBuilder(
          int index) {
        if (bikesBuilder_ == null) {
          return bikes_.get(index);  } else {
          return bikesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public java.util.List<? extends com.yzh.rfid.app.response.Bike.SimpleBikeMessageOrBuilder> 
           getBikesOrBuilderList() {
        if (bikesBuilder_ != null) {
          return bikesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bikes_);
        }
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public com.yzh.rfid.app.response.Bike.SimpleBikeMessage.Builder addBikesBuilder() {
        return getBikesFieldBuilder().addBuilder(
            com.yzh.rfid.app.response.Bike.SimpleBikeMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public com.yzh.rfid.app.response.Bike.SimpleBikeMessage.Builder addBikesBuilder(
          int index) {
        return getBikesFieldBuilder().addBuilder(
            index, com.yzh.rfid.app.response.Bike.SimpleBikeMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .SimpleBikeMessage bikes = 2;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.Bike.SimpleBikeMessage.Builder> 
           getBikesBuilderList() {
        return getBikesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.Bike.SimpleBikeMessage, com.yzh.rfid.app.response.Bike.SimpleBikeMessage.Builder, com.yzh.rfid.app.response.Bike.SimpleBikeMessageOrBuilder> 
          getBikesFieldBuilder() {
        if (bikesBuilder_ == null) {
          bikesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yzh.rfid.app.response.Bike.SimpleBikeMessage, com.yzh.rfid.app.response.Bike.SimpleBikeMessage.Builder, com.yzh.rfid.app.response.Bike.SimpleBikeMessageOrBuilder>(
                  bikes_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          bikes_ = null;
        }
        return bikesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetSimpleBikesResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:GetSimpleBikesResponseMessage)
    private static final com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage();
    }

    public static com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetSimpleBikesResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetSimpleBikesResponseMessage>() {
      public GetSimpleBikesResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetSimpleBikesResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetSimpleBikesResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetSimpleBikesResponseMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.response.GetSimpleBikesResponse.GetSimpleBikesResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetSimpleBikesResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetSimpleBikesResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034GetSimpleBikesResponse.proto\032\032ErrorMes" +
      "sageResponse.proto\032\nBike.proto\"c\n\035GetSim" +
      "pleBikesResponseMessage\022\037\n\010errorMsg\030\001 \001(" +
      "\0132\r.ErrorMessage\022!\n\005bikes\030\002 \003(\0132\022.Simple" +
      "BikeMessageB7\n\035com.yzh.rfid.app.resp" +
      "onseB\026GetSimpleBikesResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor(),
          com.yzh.rfid.app.response.Bike.getDescriptor(),
        }, assigner);
    internal_static_GetSimpleBikesResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetSimpleBikesResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetSimpleBikesResponseMessage_descriptor,
        new String[] { "ErrorMsg", "Bikes", });
    com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor();
    com.yzh.rfid.app.response.Bike.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
