// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Insurance.proto

package com.yzh.rfid.app.response;

public final class Insurance {
  private Insurance() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InsuranceMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InsuranceMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string insuranceType = 2;</code>
     */
    String getInsuranceType();
    /**
     * <code>optional string insuranceType = 2;</code>
     */
    com.google.protobuf.ByteString
        getInsuranceTypeBytes();

    /**
     * <code>optional double insuranceAmount = 3;</code>
     */
    double getInsuranceAmount();

    /**
     * <code>optional double compensationAmount = 4;</code>
     */
    double getCompensationAmount();

    /**
     * <code>optional string insuranceCompany = 5;</code>
     */
    String getInsuranceCompany();
    /**
     * <code>optional string insuranceCompany = 5;</code>
     */
    com.google.protobuf.ByteString
        getInsuranceCompanyBytes();

    /**
     * <code>optional int32 validMonth = 6;</code>
     */
    int getValidMonth();

    /**
     * <code>optional string insuranceDesc = 7;</code>
     */
    String getInsuranceDesc();
    /**
     * <code>optional string insuranceDesc = 7;</code>
     */
    com.google.protobuf.ByteString
        getInsuranceDescBytes();

    /**
     * <code>optional string createBy = 8;</code>
     */
    String getCreateBy();
    /**
     * <code>optional string createBy = 8;</code>
     */
    com.google.protobuf.ByteString
        getCreateByBytes();

    /**
     * <code>optional int64 createDate = 9;</code>
     */
    long getCreateDate();

    /**
     * <code>optional string updateBy = 10;</code>
     */
    String getUpdateBy();
    /**
     * <code>optional string updateBy = 10;</code>
     */
    com.google.protobuf.ByteString
        getUpdateByBytes();

    /**
     * <code>optional int64 updateDate = 11;</code>
     */
    long getUpdateDate();

    /**
     * <code>optional string remarks = 12;</code>
     */
    String getRemarks();
    /**
     * <code>optional string remarks = 12;</code>
     */
    com.google.protobuf.ByteString
        getRemarksBytes();

    /**
     * <code>optional string delFlag = 13;</code>
     */
    String getDelFlag();
    /**
     * <code>optional string delFlag = 13;</code>
     */
    com.google.protobuf.ByteString
        getDelFlagBytes();
  }
  /**
   * <pre>
   * [归属公安app]  保险信息
   * </pre>
   *
   * Protobuf type {@code InsuranceMessage}
   */
  public  static final class InsuranceMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InsuranceMessage)
      InsuranceMessageOrBuilder {
    // Use InsuranceMessage.newBuilder() to construct.
    private InsuranceMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InsuranceMessage() {
      id_ = 0L;
      insuranceType_ = "";
      insuranceAmount_ = 0D;
      compensationAmount_ = 0D;
      insuranceCompany_ = "";
      validMonth_ = 0;
      insuranceDesc_ = "";
      createBy_ = "";
      createDate_ = 0L;
      updateBy_ = "";
      updateDate_ = 0L;
      remarks_ = "";
      delFlag_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InsuranceMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              insuranceType_ = s;
              break;
            }
            case 25: {

              insuranceAmount_ = input.readDouble();
              break;
            }
            case 33: {

              compensationAmount_ = input.readDouble();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              insuranceCompany_ = s;
              break;
            }
            case 48: {

              validMonth_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              insuranceDesc_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              createBy_ = s;
              break;
            }
            case 72: {

              createDate_ = input.readInt64();
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              updateBy_ = s;
              break;
            }
            case 88: {

              updateDate_ = input.readInt64();
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              remarks_ = s;
              break;
            }
            case 106: {
              String s = input.readStringRequireUtf8();

              delFlag_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.response.Insurance.internal_static_InsuranceMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.response.Insurance.internal_static_InsuranceMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.response.Insurance.InsuranceMessage.class, com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int INSURANCETYPE_FIELD_NUMBER = 2;
    private volatile Object insuranceType_;
    /**
     * <code>optional string insuranceType = 2;</code>
     */
    public String getInsuranceType() {
      Object ref = insuranceType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        insuranceType_ = s;
        return s;
      }
    }
    /**
     * <code>optional string insuranceType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInsuranceTypeBytes() {
      Object ref = insuranceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        insuranceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INSURANCEAMOUNT_FIELD_NUMBER = 3;
    private double insuranceAmount_;
    /**
     * <code>optional double insuranceAmount = 3;</code>
     */
    public double getInsuranceAmount() {
      return insuranceAmount_;
    }

    public static final int COMPENSATIONAMOUNT_FIELD_NUMBER = 4;
    private double compensationAmount_;
    /**
     * <code>optional double compensationAmount = 4;</code>
     */
    public double getCompensationAmount() {
      return compensationAmount_;
    }

    public static final int INSURANCECOMPANY_FIELD_NUMBER = 5;
    private volatile Object insuranceCompany_;
    /**
     * <code>optional string insuranceCompany = 5;</code>
     */
    public String getInsuranceCompany() {
      Object ref = insuranceCompany_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        insuranceCompany_ = s;
        return s;
      }
    }
    /**
     * <code>optional string insuranceCompany = 5;</code>
     */
    public com.google.protobuf.ByteString
        getInsuranceCompanyBytes() {
      Object ref = insuranceCompany_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        insuranceCompany_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALIDMONTH_FIELD_NUMBER = 6;
    private int validMonth_;
    /**
     * <code>optional int32 validMonth = 6;</code>
     */
    public int getValidMonth() {
      return validMonth_;
    }

    public static final int INSURANCEDESC_FIELD_NUMBER = 7;
    private volatile Object insuranceDesc_;
    /**
     * <code>optional string insuranceDesc = 7;</code>
     */
    public String getInsuranceDesc() {
      Object ref = insuranceDesc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        insuranceDesc_ = s;
        return s;
      }
    }
    /**
     * <code>optional string insuranceDesc = 7;</code>
     */
    public com.google.protobuf.ByteString
        getInsuranceDescBytes() {
      Object ref = insuranceDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        insuranceDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEBY_FIELD_NUMBER = 8;
    private volatile Object createBy_;
    /**
     * <code>optional string createBy = 8;</code>
     */
    public String getCreateBy() {
      Object ref = createBy_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        createBy_ = s;
        return s;
      }
    }
    /**
     * <code>optional string createBy = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCreateByBytes() {
      Object ref = createBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        createBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEDATE_FIELD_NUMBER = 9;
    private long createDate_;
    /**
     * <code>optional int64 createDate = 9;</code>
     */
    public long getCreateDate() {
      return createDate_;
    }

    public static final int UPDATEBY_FIELD_NUMBER = 10;
    private volatile Object updateBy_;
    /**
     * <code>optional string updateBy = 10;</code>
     */
    public String getUpdateBy() {
      Object ref = updateBy_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        updateBy_ = s;
        return s;
      }
    }
    /**
     * <code>optional string updateBy = 10;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateByBytes() {
      Object ref = updateBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        updateBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATEDATE_FIELD_NUMBER = 11;
    private long updateDate_;
    /**
     * <code>optional int64 updateDate = 11;</code>
     */
    public long getUpdateDate() {
      return updateDate_;
    }

    public static final int REMARKS_FIELD_NUMBER = 12;
    private volatile Object remarks_;
    /**
     * <code>optional string remarks = 12;</code>
     */
    public String getRemarks() {
      Object ref = remarks_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        remarks_ = s;
        return s;
      }
    }
    /**
     * <code>optional string remarks = 12;</code>
     */
    public com.google.protobuf.ByteString
        getRemarksBytes() {
      Object ref = remarks_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        remarks_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELFLAG_FIELD_NUMBER = 13;
    private volatile Object delFlag_;
    /**
     * <code>optional string delFlag = 13;</code>
     */
    public String getDelFlag() {
      Object ref = delFlag_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        delFlag_ = s;
        return s;
      }
    }
    /**
     * <code>optional string delFlag = 13;</code>
     */
    public com.google.protobuf.ByteString
        getDelFlagBytes() {
      Object ref = delFlag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        delFlag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getInsuranceTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, insuranceType_);
      }
      if (insuranceAmount_ != 0D) {
        output.writeDouble(3, insuranceAmount_);
      }
      if (compensationAmount_ != 0D) {
        output.writeDouble(4, compensationAmount_);
      }
      if (!getInsuranceCompanyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, insuranceCompany_);
      }
      if (validMonth_ != 0) {
        output.writeInt32(6, validMonth_);
      }
      if (!getInsuranceDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, insuranceDesc_);
      }
      if (!getCreateByBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, createBy_);
      }
      if (createDate_ != 0L) {
        output.writeInt64(9, createDate_);
      }
      if (!getUpdateByBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, updateBy_);
      }
      if (updateDate_ != 0L) {
        output.writeInt64(11, updateDate_);
      }
      if (!getRemarksBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, remarks_);
      }
      if (!getDelFlagBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, delFlag_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getInsuranceTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, insuranceType_);
      }
      if (insuranceAmount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, insuranceAmount_);
      }
      if (compensationAmount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, compensationAmount_);
      }
      if (!getInsuranceCompanyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, insuranceCompany_);
      }
      if (validMonth_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, validMonth_);
      }
      if (!getInsuranceDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, insuranceDesc_);
      }
      if (!getCreateByBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, createBy_);
      }
      if (createDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, createDate_);
      }
      if (!getUpdateByBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, updateBy_);
      }
      if (updateDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, updateDate_);
      }
      if (!getRemarksBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, remarks_);
      }
      if (!getDelFlagBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, delFlag_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.response.Insurance.InsuranceMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.response.Insurance.InsuranceMessage other = (com.yzh.rfid.app.response.Insurance.InsuranceMessage) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getInsuranceType()
          .equals(other.getInsuranceType());
      result = result && (
          Double.doubleToLongBits(getInsuranceAmount())
          == Double.doubleToLongBits(
              other.getInsuranceAmount()));
      result = result && (
          Double.doubleToLongBits(getCompensationAmount())
          == Double.doubleToLongBits(
              other.getCompensationAmount()));
      result = result && getInsuranceCompany()
          .equals(other.getInsuranceCompany());
      result = result && (getValidMonth()
          == other.getValidMonth());
      result = result && getInsuranceDesc()
          .equals(other.getInsuranceDesc());
      result = result && getCreateBy()
          .equals(other.getCreateBy());
      result = result && (getCreateDate()
          == other.getCreateDate());
      result = result && getUpdateBy()
          .equals(other.getUpdateBy());
      result = result && (getUpdateDate()
          == other.getUpdateDate());
      result = result && getRemarks()
          .equals(other.getRemarks());
      result = result && getDelFlag()
          .equals(other.getDelFlag());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + INSURANCETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getInsuranceType().hashCode();
      hash = (37 * hash) + INSURANCEAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getInsuranceAmount()));
      hash = (37 * hash) + COMPENSATIONAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getCompensationAmount()));
      hash = (37 * hash) + INSURANCECOMPANY_FIELD_NUMBER;
      hash = (53 * hash) + getInsuranceCompany().hashCode();
      hash = (37 * hash) + VALIDMONTH_FIELD_NUMBER;
      hash = (53 * hash) + getValidMonth();
      hash = (37 * hash) + INSURANCEDESC_FIELD_NUMBER;
      hash = (53 * hash) + getInsuranceDesc().hashCode();
      hash = (37 * hash) + CREATEBY_FIELD_NUMBER;
      hash = (53 * hash) + getCreateBy().hashCode();
      hash = (37 * hash) + CREATEDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateDate());
      hash = (37 * hash) + UPDATEBY_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateBy().hashCode();
      hash = (37 * hash) + UPDATEDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdateDate());
      hash = (37 * hash) + REMARKS_FIELD_NUMBER;
      hash = (53 * hash) + getRemarks().hashCode();
      hash = (37 * hash) + DELFLAG_FIELD_NUMBER;
      hash = (53 * hash) + getDelFlag().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.response.Insurance.InsuranceMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.Insurance.InsuranceMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.Insurance.InsuranceMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.Insurance.InsuranceMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.Insurance.InsuranceMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.Insurance.InsuranceMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.Insurance.InsuranceMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.Insurance.InsuranceMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.Insurance.InsuranceMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.Insurance.InsuranceMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.response.Insurance.InsuranceMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [归属公安app]  保险信息
     * </pre>
     *
     * Protobuf type {@code InsuranceMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InsuranceMessage)
        com.yzh.rfid.app.response.Insurance.InsuranceMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.response.Insurance.internal_static_InsuranceMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.response.Insurance.internal_static_InsuranceMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.response.Insurance.InsuranceMessage.class, com.yzh.rfid.app.response.Insurance.InsuranceMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.response.Insurance.InsuranceMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        insuranceType_ = "";

        insuranceAmount_ = 0D;

        compensationAmount_ = 0D;

        insuranceCompany_ = "";

        validMonth_ = 0;

        insuranceDesc_ = "";

        createBy_ = "";

        createDate_ = 0L;

        updateBy_ = "";

        updateDate_ = 0L;

        remarks_ = "";

        delFlag_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.response.Insurance.internal_static_InsuranceMessage_descriptor;
      }

      public com.yzh.rfid.app.response.Insurance.InsuranceMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.response.Insurance.InsuranceMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.response.Insurance.InsuranceMessage build() {
        com.yzh.rfid.app.response.Insurance.InsuranceMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.response.Insurance.InsuranceMessage buildPartial() {
        com.yzh.rfid.app.response.Insurance.InsuranceMessage result = new com.yzh.rfid.app.response.Insurance.InsuranceMessage(this);
        result.id_ = id_;
        result.insuranceType_ = insuranceType_;
        result.insuranceAmount_ = insuranceAmount_;
        result.compensationAmount_ = compensationAmount_;
        result.insuranceCompany_ = insuranceCompany_;
        result.validMonth_ = validMonth_;
        result.insuranceDesc_ = insuranceDesc_;
        result.createBy_ = createBy_;
        result.createDate_ = createDate_;
        result.updateBy_ = updateBy_;
        result.updateDate_ = updateDate_;
        result.remarks_ = remarks_;
        result.delFlag_ = delFlag_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.response.Insurance.InsuranceMessage) {
          return mergeFrom((com.yzh.rfid.app.response.Insurance.InsuranceMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.response.Insurance.InsuranceMessage other) {
        if (other == com.yzh.rfid.app.response.Insurance.InsuranceMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getInsuranceType().isEmpty()) {
          insuranceType_ = other.insuranceType_;
          onChanged();
        }
        if (other.getInsuranceAmount() != 0D) {
          setInsuranceAmount(other.getInsuranceAmount());
        }
        if (other.getCompensationAmount() != 0D) {
          setCompensationAmount(other.getCompensationAmount());
        }
        if (!other.getInsuranceCompany().isEmpty()) {
          insuranceCompany_ = other.insuranceCompany_;
          onChanged();
        }
        if (other.getValidMonth() != 0) {
          setValidMonth(other.getValidMonth());
        }
        if (!other.getInsuranceDesc().isEmpty()) {
          insuranceDesc_ = other.insuranceDesc_;
          onChanged();
        }
        if (!other.getCreateBy().isEmpty()) {
          createBy_ = other.createBy_;
          onChanged();
        }
        if (other.getCreateDate() != 0L) {
          setCreateDate(other.getCreateDate());
        }
        if (!other.getUpdateBy().isEmpty()) {
          updateBy_ = other.updateBy_;
          onChanged();
        }
        if (other.getUpdateDate() != 0L) {
          setUpdateDate(other.getUpdateDate());
        }
        if (!other.getRemarks().isEmpty()) {
          remarks_ = other.remarks_;
          onChanged();
        }
        if (!other.getDelFlag().isEmpty()) {
          delFlag_ = other.delFlag_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.response.Insurance.InsuranceMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.response.Insurance.InsuranceMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private Object insuranceType_ = "";
      /**
       * <code>optional string insuranceType = 2;</code>
       */
      public String getInsuranceType() {
        Object ref = insuranceType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          insuranceType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string insuranceType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInsuranceTypeBytes() {
        Object ref = insuranceType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          insuranceType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string insuranceType = 2;</code>
       */
      public Builder setInsuranceType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        insuranceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string insuranceType = 2;</code>
       */
      public Builder clearInsuranceType() {
        
        insuranceType_ = getDefaultInstance().getInsuranceType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string insuranceType = 2;</code>
       */
      public Builder setInsuranceTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        insuranceType_ = value;
        onChanged();
        return this;
      }

      private double insuranceAmount_ ;
      /**
       * <code>optional double insuranceAmount = 3;</code>
       */
      public double getInsuranceAmount() {
        return insuranceAmount_;
      }
      /**
       * <code>optional double insuranceAmount = 3;</code>
       */
      public Builder setInsuranceAmount(double value) {
        
        insuranceAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double insuranceAmount = 3;</code>
       */
      public Builder clearInsuranceAmount() {
        
        insuranceAmount_ = 0D;
        onChanged();
        return this;
      }

      private double compensationAmount_ ;
      /**
       * <code>optional double compensationAmount = 4;</code>
       */
      public double getCompensationAmount() {
        return compensationAmount_;
      }
      /**
       * <code>optional double compensationAmount = 4;</code>
       */
      public Builder setCompensationAmount(double value) {
        
        compensationAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double compensationAmount = 4;</code>
       */
      public Builder clearCompensationAmount() {
        
        compensationAmount_ = 0D;
        onChanged();
        return this;
      }

      private Object insuranceCompany_ = "";
      /**
       * <code>optional string insuranceCompany = 5;</code>
       */
      public String getInsuranceCompany() {
        Object ref = insuranceCompany_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          insuranceCompany_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string insuranceCompany = 5;</code>
       */
      public com.google.protobuf.ByteString
          getInsuranceCompanyBytes() {
        Object ref = insuranceCompany_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          insuranceCompany_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string insuranceCompany = 5;</code>
       */
      public Builder setInsuranceCompany(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        insuranceCompany_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string insuranceCompany = 5;</code>
       */
      public Builder clearInsuranceCompany() {
        
        insuranceCompany_ = getDefaultInstance().getInsuranceCompany();
        onChanged();
        return this;
      }
      /**
       * <code>optional string insuranceCompany = 5;</code>
       */
      public Builder setInsuranceCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        insuranceCompany_ = value;
        onChanged();
        return this;
      }

      private int validMonth_ ;
      /**
       * <code>optional int32 validMonth = 6;</code>
       */
      public int getValidMonth() {
        return validMonth_;
      }
      /**
       * <code>optional int32 validMonth = 6;</code>
       */
      public Builder setValidMonth(int value) {
        
        validMonth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 validMonth = 6;</code>
       */
      public Builder clearValidMonth() {
        
        validMonth_ = 0;
        onChanged();
        return this;
      }

      private Object insuranceDesc_ = "";
      /**
       * <code>optional string insuranceDesc = 7;</code>
       */
      public String getInsuranceDesc() {
        Object ref = insuranceDesc_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          insuranceDesc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string insuranceDesc = 7;</code>
       */
      public com.google.protobuf.ByteString
          getInsuranceDescBytes() {
        Object ref = insuranceDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          insuranceDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string insuranceDesc = 7;</code>
       */
      public Builder setInsuranceDesc(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        insuranceDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string insuranceDesc = 7;</code>
       */
      public Builder clearInsuranceDesc() {
        
        insuranceDesc_ = getDefaultInstance().getInsuranceDesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string insuranceDesc = 7;</code>
       */
      public Builder setInsuranceDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        insuranceDesc_ = value;
        onChanged();
        return this;
      }

      private Object createBy_ = "";
      /**
       * <code>optional string createBy = 8;</code>
       */
      public String getCreateBy() {
        Object ref = createBy_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          createBy_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string createBy = 8;</code>
       */
      public com.google.protobuf.ByteString
          getCreateByBytes() {
        Object ref = createBy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          createBy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string createBy = 8;</code>
       */
      public Builder setCreateBy(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        createBy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string createBy = 8;</code>
       */
      public Builder clearCreateBy() {
        
        createBy_ = getDefaultInstance().getCreateBy();
        onChanged();
        return this;
      }
      /**
       * <code>optional string createBy = 8;</code>
       */
      public Builder setCreateByBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        createBy_ = value;
        onChanged();
        return this;
      }

      private long createDate_ ;
      /**
       * <code>optional int64 createDate = 9;</code>
       */
      public long getCreateDate() {
        return createDate_;
      }
      /**
       * <code>optional int64 createDate = 9;</code>
       */
      public Builder setCreateDate(long value) {
        
        createDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 createDate = 9;</code>
       */
      public Builder clearCreateDate() {
        
        createDate_ = 0L;
        onChanged();
        return this;
      }

      private Object updateBy_ = "";
      /**
       * <code>optional string updateBy = 10;</code>
       */
      public String getUpdateBy() {
        Object ref = updateBy_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          updateBy_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string updateBy = 10;</code>
       */
      public com.google.protobuf.ByteString
          getUpdateByBytes() {
        Object ref = updateBy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          updateBy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string updateBy = 10;</code>
       */
      public Builder setUpdateBy(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        updateBy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string updateBy = 10;</code>
       */
      public Builder clearUpdateBy() {
        
        updateBy_ = getDefaultInstance().getUpdateBy();
        onChanged();
        return this;
      }
      /**
       * <code>optional string updateBy = 10;</code>
       */
      public Builder setUpdateByBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        updateBy_ = value;
        onChanged();
        return this;
      }

      private long updateDate_ ;
      /**
       * <code>optional int64 updateDate = 11;</code>
       */
      public long getUpdateDate() {
        return updateDate_;
      }
      /**
       * <code>optional int64 updateDate = 11;</code>
       */
      public Builder setUpdateDate(long value) {
        
        updateDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 updateDate = 11;</code>
       */
      public Builder clearUpdateDate() {
        
        updateDate_ = 0L;
        onChanged();
        return this;
      }

      private Object remarks_ = "";
      /**
       * <code>optional string remarks = 12;</code>
       */
      public String getRemarks() {
        Object ref = remarks_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          remarks_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string remarks = 12;</code>
       */
      public com.google.protobuf.ByteString
          getRemarksBytes() {
        Object ref = remarks_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          remarks_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string remarks = 12;</code>
       */
      public Builder setRemarks(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remarks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string remarks = 12;</code>
       */
      public Builder clearRemarks() {
        
        remarks_ = getDefaultInstance().getRemarks();
        onChanged();
        return this;
      }
      /**
       * <code>optional string remarks = 12;</code>
       */
      public Builder setRemarksBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remarks_ = value;
        onChanged();
        return this;
      }

      private Object delFlag_ = "";
      /**
       * <code>optional string delFlag = 13;</code>
       */
      public String getDelFlag() {
        Object ref = delFlag_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          delFlag_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string delFlag = 13;</code>
       */
      public com.google.protobuf.ByteString
          getDelFlagBytes() {
        Object ref = delFlag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          delFlag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string delFlag = 13;</code>
       */
      public Builder setDelFlag(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        delFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string delFlag = 13;</code>
       */
      public Builder clearDelFlag() {
        
        delFlag_ = getDefaultInstance().getDelFlag();
        onChanged();
        return this;
      }
      /**
       * <code>optional string delFlag = 13;</code>
       */
      public Builder setDelFlagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        delFlag_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:InsuranceMessage)
    }

    // @@protoc_insertion_point(class_scope:InsuranceMessage)
    private static final com.yzh.rfid.app.response.Insurance.InsuranceMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.response.Insurance.InsuranceMessage();
    }

    public static com.yzh.rfid.app.response.Insurance.InsuranceMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InsuranceMessage>
        PARSER = new com.google.protobuf.AbstractParser<InsuranceMessage>() {
      public InsuranceMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InsuranceMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InsuranceMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InsuranceMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.response.Insurance.InsuranceMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InsuranceMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InsuranceMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017Insurance.proto\"\235\002\n\020InsuranceMessage\022\n" +
      "\n\002id\030\001 \001(\003\022\025\n\rinsuranceType\030\002 \001(\t\022\027\n\017ins" +
      "uranceAmount\030\003 \001(\001\022\032\n\022compensationAmount" +
      "\030\004 \001(\001\022\030\n\020insuranceCompany\030\005 \001(\t\022\022\n\nvali" +
      "dMonth\030\006 \001(\005\022\025\n\rinsuranceDesc\030\007 \001(\t\022\020\n\010c" +
      "reateBy\030\010 \001(\t\022\022\n\ncreateDate\030\t \001(\003\022\020\n\010upd" +
      "ateBy\030\n \001(\t\022\022\n\nupdateDate\030\013 \001(\003\022\017\n\007remar" +
      "ks\030\014 \001(\t\022\017\n\007delFlag\030\r \001(\tB*\n\035com.yzh.rfi" +
      "dbike.app.responseB\tInsuranceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_InsuranceMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InsuranceMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InsuranceMessage_descriptor,
        new String[] { "Id", "InsuranceType", "InsuranceAmount", "CompensationAmount", "InsuranceCompany", "ValidMonth", "InsuranceDesc", "CreateBy", "CreateDate", "UpdateBy", "UpdateDate", "Remarks", "DelFlag", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
